{"nodes":[{"content":"The exception that is thrown when binding to a member results in more than one member matching the binding criteria. This class cannot be inherited.","nodes":[{"pos":[0,148],"content":"The exception that is thrown when binding to a member results in more than one member matching the binding criteria. This class cannot be inherited.","nodes":[{"content":"The exception that is thrown when binding to a member results in more than one member matching the binding criteria. This class cannot be inherited.","pos":[0,148],"nodes":[{"content":"The exception that is thrown when binding to a member results in more than one member matching the binding criteria.","pos":[0,116]},{"content":"This class cannot be inherited.","pos":[117,148]}]}]}],"pos":[673,822],"yaml":true},{"content":"`AmbiguousMatchException` uses the HRESULT COR_E_AMBIGUOUSMATCH which has the value 0x8000211D.  \n  \n An `AmbiguousMatchException` is thrown when a member is invoked late-bound and multiple overloads satisfy the binding criteria, or when more than one member matches the binding criteria passed to a reflection method that can return only a single result (for example, <xref:System.Type.GetMethod%2A?displayProperty=fullName> or <xref:System.Type.GetProperty%2A?displayProperty=fullName>).","nodes":[{"pos":[0,95],"content":"<ph id=\"ph1\">`AmbiguousMatchException`</ph> uses the HRESULT COR_E_AMBIGUOUSMATCH which has the value 0x8000211D.","source":"`AmbiguousMatchException` uses the HRESULT COR_E_AMBIGUOUSMATCH which has the value 0x8000211D."},{"pos":[102,489],"content":"An <ph id=\"ph1\">`AmbiguousMatchException`</ph> is thrown when a member is invoked late-bound and multiple overloads satisfy the binding criteria, or when more than one member matches the binding criteria passed to a reflection method that can return only a single result (for example, <ph id=\"ph2\">&lt;xref:System.Type.GetMethod%2A?displayProperty=fullName&gt;</ph> or <ph id=\"ph3\">&lt;xref:System.Type.GetProperty%2A?displayProperty=fullName&gt;</ph>).","source":"An `AmbiguousMatchException` is thrown when a member is invoked late-bound and multiple overloads satisfy the binding criteria, or when more than one member matches the binding criteria passed to a reflection method that can return only a single result (for example, <xref:System.Type.GetMethod%2A?displayProperty=fullName> or <xref:System.Type.GetProperty%2A?displayProperty=fullName>)."}],"pos":[833,1327],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with an empty message string and the root cause exception set to `null`.","nodes":[{"pos":[0,175],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Reflection.AmbiguousMatchException\"&gt;&lt;/xref&gt;</ph> class with an empty message string and the root cause exception set to <ph id=\"ph2\">`null`</ph>.","source":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with an empty message string and the root cause exception set to `null`."}],"pos":[3969,4145],"yaml":true},{"content":"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`|  \n|<xref:System.Exception.Message%2A>|The empty string (\"\").|","nodes":[{"pos":[0,160],"content":"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.","nodes":[{"content":"<ph id=\"ph1\">`AmbiguousMatchException`</ph> inherits from <ph id=\"ph2\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,64],"source":"`AmbiguousMatchException` inherits from <xref:System.Exception>."},{"content":"This constructor sets the properties of the <ph id=\"ph1\">`Exception`</ph> object as shown in the following table.","pos":[65,160],"source":" This constructor sets the properties of the `Exception` object as shown in the following table."}]},{"pos":[167,175],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[176,181],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[217,258],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[270,304],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[305,327],"content":"The empty string (\"\").","nodes":[{"content":"The empty string (\"\").","pos":[0,22]}]}],"pos":[4156,4494],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with its message string set to the given message and the root cause exception set to `null`.","nodes":[{"pos":[0,195],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Reflection.AmbiguousMatchException\"&gt;&lt;/xref&gt;</ph> class with its message string set to the given message and the root cause exception set to <ph id=\"ph2\">`null`</ph>.","source":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with its message string set to the given message and the root cause exception set to `null`."}],"pos":[6306,6502],"yaml":true},{"content":"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`|  \n|<xref:System.Exception.Message%2A>|The `message` string.|","nodes":[{"pos":[0,160],"content":"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.","nodes":[{"content":"<ph id=\"ph1\">`AmbiguousMatchException`</ph> inherits from <ph id=\"ph2\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,64],"source":"`AmbiguousMatchException` inherits from <xref:System.Exception>."},{"content":"This constructor sets the properties of the <ph id=\"ph1\">`Exception`</ph> object as shown in the following table.","pos":[65,160],"source":" This constructor sets the properties of the `Exception` object as shown in the following table."}]},{"pos":[167,175],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[176,181],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[217,258],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[270,304],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[305,326],"content":"The <ph id=\"ph1\">`message`</ph> string.","source":"The `message` string."}],"pos":[6513,6848],"yaml":true,"extradata":"MT"},{"content":"A string indicating the reason this exception was thrown.","nodes":[{"pos":[0,57],"content":"A string indicating the reason this exception was thrown.","nodes":[{"content":"A string indicating the reason this exception was thrown.","pos":[0,57]}]}],"pos":[6999,7057],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,209],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Reflection.AmbiguousMatchException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[8876,9086],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.Reflection.AmbiguousMatchException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,556],"content":"The following table shows the initial property values for an instance of <xref:System.Reflection.AmbiguousMatchException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Reflection.AmbiguousMatchException&gt;</ph>.","pos":[0,122],"source":"The following table shows the initial property values for an instance of <xref:System.Reflection.AmbiguousMatchException>."}]},{"pos":[563,571],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[572,577],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[613,654],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[655,685],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[690,724],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[725,750],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[9097,9858],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[11017,11079],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,193],"content":"The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">inner</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,193],"source":" If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[11143,11337],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Reflection.AmbiguousMatchException\n  commentId: T:System.Reflection.AmbiguousMatchException\n  id: AmbiguousMatchException\n  children:\n  - System.Reflection.AmbiguousMatchException.#ctor\n  - System.Reflection.AmbiguousMatchException.#ctor(System.String)\n  - System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: AmbiguousMatchException\n  nameWithType: AmbiguousMatchException\n  fullName: System.Reflection.AmbiguousMatchException\n  type: Class\n  assemblies:\n  - System.Reflection\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System.Reflection\n  summary: The exception that is thrown when binding to a member results in more than one member matching the binding criteria. This class cannot be inherited.\n  remarks: \"`AmbiguousMatchException` uses the HRESULT COR_E_AMBIGUOUSMATCH which has the value 0x8000211D.  \\n  \\n An `AmbiguousMatchException` is thrown when a member is invoked late-bound and multiple overloads satisfy the binding criteria, or when more than one member matches the binding criteria passed to a reflection method that can return only a single result (for example, <xref:System.Type.GetMethod%2A?displayProperty=fullName> or <xref:System.Type.GetProperty%2A?displayProperty=fullName>).\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public sealed class AmbiguousMatchException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Reflection/AmbiguousMatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Reflection.AmbiguousMatchException.#ctor\n  commentId: M:System.Reflection.AmbiguousMatchException.#ctor\n  id: '#ctor'\n  parent: System.Reflection.AmbiguousMatchException\n  langs:\n  - csharp\n  name: AmbiguousMatchException()\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException()\n  fullName: AmbiguousMatchException.AmbiguousMatchException()\n  type: Constructor\n  assemblies:\n  - System.Reflection\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System.Reflection\n  summary: Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with an empty message string and the root cause exception set to `null`.\n  remarks: \"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|The empty string (\\\"\\\").|\"\n  syntax:\n    content: public AmbiguousMatchException ();\n    parameters: []\n  overload: System.Reflection.AmbiguousMatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Reflection/AmbiguousMatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String)\n  commentId: M:System.Reflection.AmbiguousMatchException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Reflection.AmbiguousMatchException\n  langs:\n  - csharp\n  name: AmbiguousMatchException(String)\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException(String)\n  fullName: AmbiguousMatchException.AmbiguousMatchException(String)\n  type: Constructor\n  assemblies:\n  - System.Reflection\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System.Reflection\n  summary: Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with its message string set to the given message and the root cause exception set to `null`.\n  remarks: \"`AmbiguousMatchException` inherits from <xref:System.Exception>. This constructor sets the properties of the `Exception` object as shown in the following table.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`|  \\n|<xref:System.Exception.Message%2A>|The `message` string.|\"\n  syntax:\n    content: public AmbiguousMatchException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A string indicating the reason this exception was thrown.\n  overload: System.Reflection.AmbiguousMatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Reflection/AmbiguousMatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)\n  commentId: M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Reflection.AmbiguousMatchException\n  langs:\n  - csharp\n  name: AmbiguousMatchException(String, Exception)\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException(String, Exception)\n  fullName: AmbiguousMatchException.AmbiguousMatchException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Reflection\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System.Reflection\n  summary: Initializes a new instance of the <xref href=\"System.Reflection.AmbiguousMatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Reflection.AmbiguousMatchException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  example:\n  - \"The following example shows two classes, each named `Mymethod`. One class takes an integer and the other takes a string. If an integer is passed to `Mymethod`, the first class is used. If a string is passed, the second class is used. If it cannot be determined which `Mymethod` to use, `AmbiguousMatchException` is thrown.  \\n  \\n [!code-cpp[Classic AmbiguousMatchException.AmbiguousMatchException2 Example#1](~/samples/snippets/cpp/VS_Snippets_CLR_Classic/classic AmbiguousMatchException.AmbiguousMatchException2 Example/CPP/source.cpp#1)]\\n [!code-csharp[Classic AmbiguousMatchException.AmbiguousMatchException2 Example#1](~/samples/snippets/csharp/VS_Snippets_CLR_Classic/classic AmbiguousMatchException.AmbiguousMatchException2 Example/CS/source.cs#1)]\\n [!code-vb[Classic AmbiguousMatchException.AmbiguousMatchException2 Example#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_Classic/classic AmbiguousMatchException.AmbiguousMatchException2 Example/VB/source.vb#1)]\"\n  syntax:\n    content: public AmbiguousMatchException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>inner</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Reflection.AmbiguousMatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Reflection/AmbiguousMatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Reflection.AmbiguousMatchException.#ctor\n  parent: System.Reflection.AmbiguousMatchException\n  isExternal: false\n  name: AmbiguousMatchException()\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException()\n  fullName: AmbiguousMatchException.AmbiguousMatchException()\n- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String)\n  parent: System.Reflection.AmbiguousMatchException\n  isExternal: false\n  name: AmbiguousMatchException(String)\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException(String)\n  fullName: AmbiguousMatchException.AmbiguousMatchException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)\n  parent: System.Reflection.AmbiguousMatchException\n  isExternal: false\n  name: AmbiguousMatchException(String, Exception)\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException(String, Exception)\n  fullName: AmbiguousMatchException.AmbiguousMatchException(String, Exception)\n- uid: System.Reflection.AmbiguousMatchException.#ctor*\n  parent: System.Reflection.AmbiguousMatchException\n  isExternal: false\n  name: AmbiguousMatchException\n  nameWithType: AmbiguousMatchException.AmbiguousMatchException\n  fullName: AmbiguousMatchException.AmbiguousMatchException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Reflection/AmbiguousMatchException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}