{"nodes":[{"content":"The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited.","nodes":[{"pos":[0,148],"content":"The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited.","nodes":[{"content":"The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited.","pos":[0,148],"nodes":[{"content":"The exception that is thrown when there is an internal error in the execution engine of the common language runtime.","pos":[0,116]},{"content":"This class cannot be inherited.","pos":[117,148]}]}]}],"pos":[583,732],"yaml":true},{"content":"There is no non-obsolete alternative to <xref:System.ExecutionEngineException>. If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method.","nodes":[{"pos":[0,195],"content":"There is no non-obsolete alternative to <xref:System.ExecutionEngineException>. If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method.","nodes":[{"content":"There is no non-obsolete alternative to <xref:System.ExecutionEngineException>. If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method.","pos":[0,195],"nodes":[{"content":"There is no non-obsolete alternative to <ph id=\"ph1\">&lt;xref:System.ExecutionEngineException&gt;</ph>.","pos":[0,79],"source":"There is no non-obsolete alternative to <xref:System.ExecutionEngineException>."},{"content":"If further execution of your application cannot be sustained, use the <ph id=\"ph1\">&lt;xref:System.Environment.FailFast%2A&gt;</ph> method.","pos":[80,195],"source":" If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method."}]}]}],"pos":[743,939],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class.","nodes":[{"pos":[0,93],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ExecutionEngineException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class."}],"pos":[3404,3498],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Internal error occurred.\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,246],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Internal error occurred.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Internal error occurred.\" This message takes into account the current system culture.","pos":[0,246],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"Internal error occurred.\"","pos":[0,186],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Internal error occurred.\""},{"content":"This message takes into account the current system culture.","pos":[187,246]}]}]},{"pos":[253,365],"content":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ExecutionEngineException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>."}]},{"pos":[372,380],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[381,386],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[422,463],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[464,509],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[514,548],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[549,584],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[3509,4106],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message.","nodes":[{"pos":[0,124],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ExecutionEngineException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message."}],"pos":[5497,5622],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A?displayProperty=fullName> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,339],"content":"This constructor initializes the <xref:System.Exception.Message%2A?displayProperty=fullName> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A?displayProperty=fullName&gt;</ph> property of the new exception using the <ph id=\"ph2\">`message`</ph> parameter.","pos":[0,153],"source":"This constructor initializes the <xref:System.Exception.Message%2A?displayProperty=fullName> property of the new exception using the `message` parameter."},{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[154,218],"source":" The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[219,339]}]},{"pos":[346,458],"content":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ExecutionEngineException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>."}]},{"pos":[465,473],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[474,479],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[515,556],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[557,602],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[607,641],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[642,667],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[5633,6311],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[6463,6501],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,199],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ExecutionEngineException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[7898,8098],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,465],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic) if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,465],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[472,584],"content":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ExecutionEngineException&gt;</ph>.","pos":[0,112],"source":"The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>."}]},{"pos":[591,599],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[600,605],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[641,682],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[683,713],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[718,752],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[753,778],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[8109,8898],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[9076,9138],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,240],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic), the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,240],"source":" If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[9211,9452],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.ExecutionEngineException\n  commentId: T:System.ExecutionEngineException\n  id: ExecutionEngineException\n  children:\n  - System.ExecutionEngineException.#ctor\n  - System.ExecutionEngineException.#ctor(System.String)\n  - System.ExecutionEngineException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ExecutionEngineException\n  nameWithType: ExecutionEngineException\n  fullName: System.ExecutionEngineException\n  type: Class\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: The exception that is thrown when there is an internal error in the execution engine of the common language runtime. This class cannot be inherited.\n  remarks: There is no non-obsolete alternative to <xref:System.ExecutionEngineException>. If further execution of your application cannot be sustained, use the <xref:System.Environment.FailFast%2A> method.\n  syntax:\n    content: >-\n      [System.Obsolete(\"This type previously indicated an unspecified fatal error in the runtime. The runtime no longer raises this exception so this type is obsolete.\")]\n\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public sealed class ExecutionEngineException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.ObsoleteAttribute\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ExecutionEngineException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ExecutionEngineException.#ctor\n  commentId: M:System.ExecutionEngineException.#ctor\n  id: '#ctor'\n  parent: System.ExecutionEngineException\n  langs:\n  - csharp\n  name: ExecutionEngineException()\n  nameWithType: ExecutionEngineException.ExecutionEngineException()\n  fullName: ExecutionEngineException.ExecutionEngineException()\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"Internal error occurred.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public ExecutionEngineException ();\n    parameters: []\n  overload: System.ExecutionEngineException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ExecutionEngineException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ExecutionEngineException.#ctor(System.String)\n  commentId: M:System.ExecutionEngineException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.ExecutionEngineException\n  langs:\n  - csharp\n  name: ExecutionEngineException(String)\n  nameWithType: ExecutionEngineException.ExecutionEngineException(String)\n  fullName: ExecutionEngineException.ExecutionEngineException(String)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A?displayProperty=fullName> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ExecutionEngineException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.ExecutionEngineException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ExecutionEngineException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)\n  commentId: M:System.ExecutionEngineException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.ExecutionEngineException\n  langs:\n  - csharp\n  name: ExecutionEngineException(String, Exception)\n  nameWithType: ExecutionEngineException.ExecutionEngineException(String, Exception)\n  fullName: ExecutionEngineException.ExecutionEngineException(String, Exception)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ExecutionEngineException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ExecutionEngineException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public ExecutionEngineException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference (`Nothing` in Visual Basic), the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.ExecutionEngineException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ExecutionEngineException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.SystemException\n  parent: System\n  isExternal: false\n  name: SystemException\n  nameWithType: SystemException\n  fullName: System.SystemException\n- uid: System.ExecutionEngineException.#ctor\n  parent: System.ExecutionEngineException\n  isExternal: false\n  name: ExecutionEngineException()\n  nameWithType: ExecutionEngineException.ExecutionEngineException()\n  fullName: ExecutionEngineException.ExecutionEngineException()\n- uid: System.ExecutionEngineException.#ctor(System.String)\n  parent: System.ExecutionEngineException\n  isExternal: false\n  name: ExecutionEngineException(String)\n  nameWithType: ExecutionEngineException.ExecutionEngineException(String)\n  fullName: ExecutionEngineException.ExecutionEngineException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)\n  parent: System.ExecutionEngineException\n  isExternal: false\n  name: ExecutionEngineException(String, Exception)\n  nameWithType: ExecutionEngineException.ExecutionEngineException(String, Exception)\n  fullName: ExecutionEngineException.ExecutionEngineException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ExecutionEngineException.#ctor*\n  parent: System.ExecutionEngineException\n  isExternal: false\n  name: ExecutionEngineException\n  nameWithType: ExecutionEngineException.ExecutionEngineException\n  fullName: ExecutionEngineException.ExecutionEngineException\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ExecutionEngineException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}