{"nodes":[{"content":"Represents an error that occurs when a dynamic bind in the C# runtime binder is processed.","nodes":[{"pos":[0,90],"content":"Represents an error that occurs when a dynamic bind in the C# runtime binder is processed.","nodes":[{"content":"Represents an error that occurs when a dynamic bind in the C# runtime binder is processed.","pos":[0,90]}]}],"pos":[864,955],"yaml":true},{"content":"Exceptions of this kind differ from <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> in that <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException> represents a failure to bind in the sense of a usual compiler error, whereas <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> represents a malfunctioning of the runtime binder itself.","nodes":[{"pos":[0,393],"content":"Exceptions of this kind differ from <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> in that <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException> represents a failure to bind in the sense of a usual compiler error, whereas <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> represents a malfunctioning of the runtime binder itself.","nodes":[{"content":"Exceptions of this kind differ from <ph id=\"ph1\">&lt;xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException&gt;</ph> in that <ph id=\"ph2\">&lt;xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException&gt;</ph> represents a failure to bind in the sense of a usual compiler error, whereas <ph id=\"ph3\">&lt;xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException&gt;</ph> represents a malfunctioning of the runtime binder itself.","pos":[0,393],"source":"Exceptions of this kind differ from <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> in that <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException> represents a failure to bind in the sense of a usual compiler error, whereas <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> represents a malfunctioning of the runtime binder itself."}]}],"pos":[966,1360],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class.","nodes":[{"pos":[0,115],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class."}],"pos":[3498,3614],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,280],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture.","pos":[0,280],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\" This message takes into account the current system culture."}]},{"pos":[287,402],"content":"The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.InsufficientMemoryException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>."}]},{"pos":[409,417],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[418,423],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[459,500],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[501,508],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[513,547],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[548,583],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[3625,4221],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message.","nodes":[{"pos":[0,150],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"&gt;&lt;/xref&gt;</ph> class that has a specified error message.","source":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message."}],"pos":[5693,5844],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","nodes":[{"pos":[0,134],"content":"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException&gt;</ph>.","pos":[0,134],"source":"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>."}]},{"pos":[141,149],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[150,155],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[191,232],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[233,240],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[245,279],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[280,328],"content":"The error message string specified in <ph id=\"ph1\">`message`</ph>.","source":"The error message string specified in `message`."}],"pos":[5855,6192],"yaml":true,"extradata":"MT"},{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"pos":[0,162],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]}],"pos":[6342,6505],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has serialized data.","nodes":[{"pos":[0,140],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"&gt;&lt;/xref&gt;</ph> class that has serialized data.","source":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has serialized data."}],"pos":[8225,8366],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","nodes":[{"pos":[0,113],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]}]}],"pos":[8377,8491],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data about the exception being thrown..","nodes":[{"pos":[0,83],"content":"The object that holds the serialized object data about the exception being thrown..","nodes":[{"content":"The object that holds the serialized object data about the exception being thrown..","pos":[0,83]}]}],"pos":[8766,8850],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[8945,9005],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,225],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"&gt;&lt;/xref&gt;</ph> class that has a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[10421,10647],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,568],"content":"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException&gt;</ph>.","pos":[0,134],"source":"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>."}]},{"pos":[575,583],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[584,589],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[625,666],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[667,674],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[679,713],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[714,762],"content":"The error message string specified in <ph id=\"ph1\">`message`</ph>.","source":"The error message string specified in `message`."}],"pos":[10658,11431],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[11607,11669],"yaml":true},{"content":"The exception that is the cause of the current exception, or a null reference if no inner exception is specified.","nodes":[{"pos":[0,113],"content":"The exception that is the cause of the current exception, or a null reference if no inner exception is specified.","nodes":[{"content":"The exception that is the cause of the current exception, or a null reference if no inner exception is specified.","pos":[0,113]}]}],"pos":[11742,11856],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  commentId: T:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  id: RuntimeBinderException\n  children:\n  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor\n  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)\n  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: RuntimeBinderException\n  nameWithType: RuntimeBinderException\n  fullName: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  type: Class\n  assemblies:\n  - Microsoft.CSharp\n  namespace: Microsoft.CSharp.RuntimeBinder\n  summary: Represents an error that occurs when a dynamic bind in the C# runtime binder is processed.\n  remarks: Exceptions of this kind differ from <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> in that <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException> represents a failure to bind in the sense of a usual compiler error, whereas <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderInternalCompilerException> represents a malfunctioning of the runtime binder itself.\n  syntax:\n    content: 'public class RuntimeBinderException : Exception'\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n  author: stevehoag\n  ms.author: shoag\n  manager: wpickett\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor\n  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor\n  id: '#ctor'\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  langs:\n  - csharp\n  name: RuntimeBinderException()\n  nameWithType: RuntimeBinderException.RuntimeBinderException()\n  fullName: RuntimeBinderException.RuntimeBinderException()\n  type: Constructor\n  assemblies:\n  - Microsoft.CSharp\n  namespace: Microsoft.CSharp.RuntimeBinder\n  summary: Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"DefaultMessageDisplayedByParameterlessCtorWriterMustSupply\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public RuntimeBinderException ();\n    parameters: []\n  overload: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n  author: stevehoag\n  ms.author: shoag\n  manager: wpickett\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)\n  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  langs:\n  - csharp\n  name: RuntimeBinderException(String)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(String)\n  fullName: RuntimeBinderException.RuntimeBinderException(String)\n  type: Constructor\n  assemblies:\n  - Microsoft.CSharp\n  namespace: Microsoft.CSharp.RuntimeBinder\n  summary: Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message.\n  remarks: \"The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public RuntimeBinderException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n  author: stevehoag\n  ms.author: shoag\n  manager: wpickett\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  langs:\n  - csharp\n  name: RuntimeBinderException(SerializationInfo, StreamingContext)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(SerializationInfo, StreamingContext)\n  fullName: RuntimeBinderException.RuntimeBinderException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - Microsoft.CSharp\n  namespace: Microsoft.CSharp.RuntimeBinder\n  summary: Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.\n  syntax:\n    content: protected RuntimeBinderException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data about the exception being thrown..\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n  author: stevehoag\n  ms.author: shoag\n  manager: wpickett\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)\n  commentId: M:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  langs:\n  - csharp\n  name: RuntimeBinderException(String, Exception)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(String, Exception)\n  fullName: RuntimeBinderException.RuntimeBinderException(String, Exception)\n  type: Constructor\n  assemblies:\n  - Microsoft.CSharp\n  namespace: Microsoft.CSharp.RuntimeBinder\n  summary: Initializes a new instance of the <xref href=\"Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\"></xref> class that has a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:Microsoft.CSharp.RuntimeBinder.RuntimeBinderException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public RuntimeBinderException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception, or a null reference if no inner exception is specified.\n  overload: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n  author: stevehoag\n  ms.author: shoag\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  isExternal: false\n  name: RuntimeBinderException()\n  nameWithType: RuntimeBinderException.RuntimeBinderException()\n  fullName: RuntimeBinderException.RuntimeBinderException()\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String)\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  isExternal: false\n  name: RuntimeBinderException(String)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(String)\n  fullName: RuntimeBinderException.RuntimeBinderException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  isExternal: false\n  name: RuntimeBinderException(SerializationInfo, StreamingContext)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(SerializationInfo, StreamingContext)\n  fullName: RuntimeBinderException.RuntimeBinderException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor(System.String,System.Exception)\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  isExternal: false\n  name: RuntimeBinderException(String, Exception)\n  nameWithType: RuntimeBinderException.RuntimeBinderException(String, Exception)\n  fullName: RuntimeBinderException.RuntimeBinderException(String, Exception)\n- uid: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException.#ctor*\n  parent: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException\n  isExternal: false\n  name: RuntimeBinderException\n  nameWithType: RuntimeBinderException.RuntimeBinderException\n  fullName: RuntimeBinderException.RuntimeBinderException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/Microsoft.CSharp.RuntimeBinder/RuntimeBinderException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}