{"nodes":[{"content":"The exception that is thrown when mapping related service requests fail.","nodes":[{"pos":[0,72],"content":"The exception that is thrown when mapping related service requests fail.","nodes":[{"content":"The exception that is thrown when mapping related service requests fail.","pos":[0,72]}]}],"pos":[521,594],"yaml":true},{"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"pos":[0,94],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"content":"For more information about how to handle exceptions in your code, see <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]}],"pos":[605,700],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref>.","nodes":[{"pos":[0,80],"content":"Initializes a new instance of <ph id=\"ph1\">&lt;xref href=\"System.Data.MappingException\"&gt;&lt;/xref&gt;</ph>.","source":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref>."}],"pos":[2618,2699],"yaml":true},{"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"pos":[0,94],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"content":"For more information about how to handle exceptions in your code, see <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]}],"pos":[2710,2805],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> with a specialized error message.","nodes":[{"pos":[0,113],"content":"Initializes a new instance of <ph id=\"ph1\">&lt;xref href=\"System.Data.MappingException\"&gt;&lt;/xref&gt;</ph> with a specialized error message.","source":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> with a specialized error message."}],"pos":[3918,4032],"yaml":true},{"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"pos":[0,94],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"content":"For more information about how to handle exceptions in your code, see <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]}],"pos":[4043,4138],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[4282,4320],"yaml":true},{"content":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> that uses a specified error message and a reference to the inner exception.","nodes":[{"pos":[0,155],"content":"Initializes a new instance of <ph id=\"ph1\">&lt;xref href=\"System.Data.MappingException\"&gt;&lt;/xref&gt;</ph> that uses a specified error message and a reference to the inner exception.","source":"Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> that uses a specified error message and a reference to the inner exception."}],"pos":[5447,5603],"yaml":true},{"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"pos":[0,94],"content":"For more information about how to handle exceptions in your code, see <xref:System.Exception>.","nodes":[{"content":"For more information about how to handle exceptions in your code, see <ph id=\"ph1\">&lt;xref:System.Exception&gt;</ph>.","pos":[0,94],"source":"For more information about how to handle exceptions in your code, see <xref:System.Exception>."}]}],"pos":[5614,5709],"yaml":true,"extradata":"MT"},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[5879,5917],"yaml":true},{"content":"The exception that is the cause of the current exception, or a null reference (`Nothing` in Visual Basic) if no inner exception is specified.","nodes":[{"pos":[0,141],"content":"The exception that is the cause of the current exception, or a null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic) if no inner exception is specified.","source":"The exception that is the cause of the current exception, or a null reference (`Nothing` in Visual Basic) if no inner exception is specified."}],"pos":[5990,6132],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Data.MappingException\n  commentId: T:System.Data.MappingException\n  id: MappingException\n  children:\n  - System.Data.MappingException.#ctor\n  - System.Data.MappingException.#ctor(System.String)\n  - System.Data.MappingException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: MappingException\n  nameWithType: MappingException\n  fullName: System.Data.MappingException\n  type: Class\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: The exception that is thrown when mapping related service requests fail.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: 'public sealed class MappingException : System.Data.EntityException'\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.SystemException\n  - System.Data.DataException\n  - System.Data.EntityException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data/MappingException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.MappingException.#ctor\n  commentId: M:System.Data.MappingException.#ctor\n  id: '#ctor'\n  parent: System.Data.MappingException\n  langs:\n  - csharp\n  name: MappingException()\n  nameWithType: MappingException.MappingException()\n  fullName: MappingException.MappingException()\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref>.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public MappingException ();\n    parameters: []\n  overload: System.Data.MappingException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data/MappingException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.MappingException.#ctor(System.String)\n  commentId: M:System.Data.MappingException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Data.MappingException\n  langs:\n  - csharp\n  name: MappingException(String)\n  nameWithType: MappingException.MappingException(String)\n  fullName: MappingException.MappingException(String)\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> with a specialized error message.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public MappingException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n  overload: System.Data.MappingException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data/MappingException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.MappingException.#ctor(System.String,System.Exception)\n  commentId: M:System.Data.MappingException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Data.MappingException\n  langs:\n  - csharp\n  name: MappingException(String, Exception)\n  nameWithType: MappingException.MappingException(String, Exception)\n  fullName: MappingException.MappingException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Data.Entity\n  namespace: System.Data\n  summary: Initializes a new instance of <xref href=\"System.Data.MappingException\"></xref> that uses a specified error message and a reference to the inner exception.\n  remarks: For more information about how to handle exceptions in your code, see <xref:System.Exception>.\n  syntax:\n    content: public MappingException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception, or a null reference (`Nothing` in Visual Basic) if no inner exception is specified.\n  overload: System.Data.MappingException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data/MappingException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\nreferences:\n- uid: System.Data.EntityException\n  parent: System.Data\n  isExternal: false\n  name: EntityException\n  nameWithType: EntityException\n  fullName: System.Data.EntityException\n- uid: System.Data.MappingException.#ctor\n  parent: System.Data.MappingException\n  isExternal: false\n  name: MappingException()\n  nameWithType: MappingException.MappingException()\n  fullName: MappingException.MappingException()\n- uid: System.Data.MappingException.#ctor(System.String)\n  parent: System.Data.MappingException\n  isExternal: false\n  name: MappingException(String)\n  nameWithType: MappingException.MappingException(String)\n  fullName: MappingException.MappingException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Data.MappingException.#ctor(System.String,System.Exception)\n  parent: System.Data.MappingException\n  isExternal: false\n  name: MappingException(String, Exception)\n  nameWithType: MappingException.MappingException(String, Exception)\n  fullName: MappingException.MappingException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Data.MappingException.#ctor*\n  parent: System.Data.MappingException\n  isExternal: false\n  name: MappingException\n  nameWithType: MappingException.MappingException\n  fullName: MappingException.MappingException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data/MappingException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}