{"nodes":[{"content":"The exception that is thrown for a general XAML reader or XAML writer exception.","nodes":[{"pos":[0,80],"content":"The exception that is thrown for a general XAML reader or XAML writer exception.","nodes":[{"content":"The exception that is thrown for a general XAML reader or XAML writer exception.","pos":[0,80]}]}],"pos":[971,1052],"yaml":true},{"content":"More specific exceptions such as <xref:System.Xaml.XamlParseException> exist and are often thrown instead of <xref:System.Xaml.XamlException>. Specific exceptions typically provide more precise exception information as properties of the exception, or just because the specific exception was raised.","nodes":[{"pos":[0,298],"content":"More specific exceptions such as <xref:System.Xaml.XamlParseException> exist and are often thrown instead of <xref:System.Xaml.XamlException>. Specific exceptions typically provide more precise exception information as properties of the exception, or just because the specific exception was raised.","nodes":[{"content":"More specific exceptions such as <xref:System.Xaml.XamlParseException> exist and are often thrown instead of <xref:System.Xaml.XamlException>. Specific exceptions typically provide more precise exception information as properties of the exception, or just because the specific exception was raised.","pos":[0,298],"nodes":[{"content":"More specific exceptions such as <ph id=\"ph1\">&lt;xref:System.Xaml.XamlParseException&gt;</ph> exist and are often thrown instead of <ph id=\"ph2\">&lt;xref:System.Xaml.XamlException&gt;</ph>.","pos":[0,142],"source":"More specific exceptions such as <xref:System.Xaml.XamlParseException> exist and are often thrown instead of <xref:System.Xaml.XamlException>."},{"content":"Specific exceptions typically provide more precise exception information as properties of the exception, or just because the specific exception was raised.","pos":[143,298]}]}]}],"pos":[1063,1362],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a system-supplied message that describes the error.","nodes":[{"pos":[0,161],"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a system-supplied message that describes the error.","nodes":[{"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Xaml.XamlException\"&gt;&lt;/xref&gt;</ph> class.","pos":[0,87],"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class."},{"content":"The instance contains a system-supplied message that describes the error.","pos":[88,161]}]}],"pos":[3220,3382],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified message that describes the error.","nodes":[{"pos":[0,155],"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified message that describes the error.","nodes":[{"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Xaml.XamlException\"&gt;&lt;/xref&gt;</ph> class.","pos":[0,87],"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class."},{"content":"The instance contains a specified message that describes the error.","pos":[88,155]}]}],"pos":[4409,4565],"yaml":true},{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"pos":[0,155],"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[0,155],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[42,155]}]}]}],"pos":[4706,4862],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class with serialized data.","nodes":[{"pos":[0,108],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Xaml.XamlException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class with serialized data."}],"pos":[6146,6255],"yaml":true},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[6521,6571],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[6666,6726],"yaml":true},{"content":"<code>info</code> is `null`.","nodes":[{"pos":[0,28],"content":"<ph id=\"ph1\">&lt;code&gt;info&lt;/code&gt;</ph> is <ph id=\"ph2\">`null`</ph>.","source":"<code>info</code> is `null`."}],"pos":[6887,6916],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,211],"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Xaml.XamlException\"&gt;&lt;/xref&gt;</ph> class.","pos":[0,87],"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class."},{"content":"The instance contains a specified error message and a reference to the inner exception that is the cause of this exception.","pos":[88,211]}]}],"pos":[7898,8110],"yaml":true},{"content":"An exception that is thrown because a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor; or it returns `null` if the <xref:System.Exception.InnerException%2A> property does not provide the inner exception value to the constructor.","nodes":[{"pos":[0,425],"content":"An exception that is thrown because a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor; or it returns `null` if the <xref:System.Exception.InnerException%2A> property does not provide the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown because a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,168],"source":"An exception that is thrown because a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor; or it returns <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not provide the inner exception value to the constructor.","pos":[169,425],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor; or it returns `null` if the <xref:System.Exception.InnerException%2A> property does not provide the inner exception value to the constructor."}]}],"pos":[8121,8547],"yaml":true,"extradata":"MT"},{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"pos":[0,155],"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[0,155],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[42,155]}]}]}],"pos":[8714,8870],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[8943,9146],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message, inner exception, and line information.","nodes":[{"pos":[0,175],"content":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message, inner exception, and line information.","nodes":[{"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Xaml.XamlException\"&gt;&lt;/xref&gt;</ph> class.","pos":[0,87],"source":"Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class."},{"content":"The instance contains a specified error message, inner exception, and line information.","pos":[88,175]}]}],"pos":[10310,10486],"yaml":true},{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"pos":[0,155],"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[0,155],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor must make sure that this string has been localized for the current system culture.","pos":[42,155]}]}]}],"pos":[10687,10843],"yaml":true},{"content":"The exception that is the cause of the current exception.","nodes":[{"pos":[0,57],"content":"The exception that is the cause of the current exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]}]}],"pos":[10916,10974],"yaml":true},{"content":"The line number to report to debugging or to line information consumers.","nodes":[{"pos":[0,72],"content":"The line number to report to debugging or to line information consumers.","nodes":[{"content":"The line number to report to debugging or to line information consumers.","pos":[0,72]}]}],"pos":[11039,11112],"yaml":true},{"content":"The line position to report to debugging or line information consumers.","nodes":[{"pos":[0,71],"content":"The line position to report to debugging or line information consumers.","nodes":[{"content":"The line position to report to debugging or line information consumers.","pos":[0,71]}]}],"pos":[11179,11251],"yaml":true},{"content":"Implements <xref href=\"System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\"></xref> and provides serialization support for the line information data.","nodes":[{"pos":[0,248],"content":"Implements <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\"&gt;&lt;/xref&gt;</ph> and provides serialization support for the line information data.","source":"Implements <xref href=\"System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\"></xref> and provides serialization support for the line information data."}],"pos":[12552,12801],"yaml":true},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[13129,13179],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[13274,13334],"yaml":true},{"content":"<code>info</code> is `null`.","nodes":[{"pos":[0,28],"content":"<ph id=\"ph1\">&lt;code&gt;info&lt;/code&gt;</ph> is <ph id=\"ph2\">`null`</ph>.","source":"<code>info</code> is `null`."}],"pos":[13503,13532],"yaml":true},{"content":"Gets or sets the line number component of XAML text line information that the exception reports.","nodes":[{"pos":[0,96],"content":"Gets or sets the line number component of XAML text line information that the exception reports.","nodes":[{"content":"Gets or sets the line number component of XAML text line information that the exception reports.","pos":[0,96]}]}],"pos":[14428,14525],"yaml":true},{"content":"The line number component of the XAML text line information.","nodes":[{"pos":[0,60],"content":"The line number component of the XAML text line information.","nodes":[{"content":"The line number component of the XAML text line information.","pos":[0,60]}]}],"pos":[14650,14711],"yaml":true},{"content":"Gets or sets the line position component of XAML text line information that the exception reports.","nodes":[{"pos":[0,98],"content":"Gets or sets the line position component of XAML text line information that the exception reports.","nodes":[{"content":"Gets or sets the line position component of XAML text line information that the exception reports.","pos":[0,98]}]}],"pos":[15620,15719],"yaml":true},{"content":"The line position component of XAML text line information.","nodes":[{"pos":[0,58],"content":"The line position component of XAML text line information.","nodes":[{"content":"The line position component of XAML text line information.","pos":[0,58]}]}],"pos":[15846,15905],"yaml":true},{"content":"Gets or sets the exception message, and if line information is available, appends the line information to the message.","nodes":[{"pos":[0,118],"content":"Gets or sets the exception message, and if line information is available, appends the line information to the message.","nodes":[{"content":"Gets or sets the exception message, and if line information is available, appends the line information to the message.","pos":[0,118]}]}],"pos":[16786,16905],"yaml":true},{"content":"<xref:System.Xaml.XamlException> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers. If line information is available, this property includes the line information. If line information is unavailable, the message is the same as the base message.","nodes":[{"pos":[0,358],"content":"<xref:System.Xaml.XamlException> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers. If line information is available, this property includes the line information. If line information is unavailable, the message is the same as the base message.","nodes":[{"content":"<xref:System.Xaml.XamlException> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers. If line information is available, this property includes the line information. If line information is unavailable, the message is the same as the base message.","pos":[0,358],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.Xaml.XamlException&gt;</ph> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers.","pos":[0,198],"source":"<xref:System.Xaml.XamlException> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers."},{"content":"If line information is available, this property includes the line information.","pos":[199,277]},{"content":"If line information is unavailable, the message is the same as the base message.","pos":[278,358]}]}]}],"pos":[16916,17275],"yaml":true,"extradata":"MT"},{"content":"The exception message that includes the appended line information.","nodes":[{"pos":[0,66],"content":"The exception message that includes the appended line information.","nodes":[{"content":"The exception message that includes the appended line information.","pos":[0,66]}]}],"pos":[17395,17462],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Xaml.XamlException\n  commentId: T:System.Xaml.XamlException\n  id: XamlException\n  children:\n  - System.Xaml.XamlException.#ctor\n  - System.Xaml.XamlException.#ctor(System.String)\n  - System.Xaml.XamlException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlException.#ctor(System.String,System.Exception)\n  - System.Xaml.XamlException.#ctor(System.String,System.Exception,System.Int32,System.Int32)\n  - System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Xaml.XamlException.LineNumber\n  - System.Xaml.XamlException.LinePosition\n  - System.Xaml.XamlException.Message\n  langs:\n  - csharp\n  name: XamlException\n  nameWithType: XamlException\n  fullName: System.Xaml.XamlException\n  type: Class\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: The exception that is thrown for a general XAML reader or XAML writer exception.\n  remarks: More specific exceptions such as <xref:System.Xaml.XamlParseException> exist and are often thrown instead of <xref:System.Xaml.XamlException>. Specific exceptions typically provide more precise exception information as properties of the exception, or just because the specific exception was raised.\n  syntax:\n    content: 'public class XamlException : Exception'\n  inheritance:\n  - System.Object\n  - System.Exception\n  derivedClasses:\n  - System.Xaml.XamlDuplicateMemberException\n  - System.Xaml.XamlInternalException\n  - System.Xaml.XamlObjectReaderException\n  - System.Xaml.XamlObjectWriterException\n  - System.Xaml.XamlParseException\n  - System.Xaml.XamlSchemaException\n  - System.Xaml.XamlXmlWriterException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.#ctor\n  commentId: M:System.Xaml.XamlException.#ctor\n  id: '#ctor'\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: XamlException()\n  nameWithType: XamlException.XamlException()\n  fullName: XamlException.XamlException()\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a system-supplied message that describes the error.\n  syntax:\n    content: public XamlException ();\n    parameters: []\n  overload: System.Xaml.XamlException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.#ctor(System.String)\n  commentId: M:System.Xaml.XamlException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: XamlException(String)\n  nameWithType: XamlException.XamlException(String)\n  fullName: XamlException.XamlException(String)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified message that describes the error.\n  syntax:\n    content: public XamlException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.\n  overload: System.Xaml.XamlException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Xaml.XamlException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: XamlException(SerializationInfo, StreamingContext)\n  nameWithType: XamlException.XamlException(SerializationInfo, StreamingContext)\n  fullName: XamlException.XamlException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class with serialized data.\n  syntax:\n    content: protected XamlException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Xaml.XamlException.#ctor*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: <code>info</code> is `null`.\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.#ctor(System.String,System.Exception)\n  commentId: M:System.Xaml.XamlException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: XamlException(String, Exception)\n  nameWithType: XamlException.XamlException(String, Exception)\n  fullName: XamlException.XamlException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: An exception that is thrown because a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor; or it returns `null` if the <xref:System.Exception.InnerException%2A> property does not provide the inner exception value to the constructor.\n  syntax:\n    content: public XamlException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Xaml.XamlException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.#ctor(System.String,System.Exception,System.Int32,System.Int32)\n  commentId: M:System.Xaml.XamlException.#ctor(System.String,System.Exception,System.Int32,System.Int32)\n  id: '#ctor(System.String,System.Exception,System.Int32,System.Int32)'\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: XamlException(String, Exception, Int32, Int32)\n  nameWithType: XamlException.XamlException(String, Exception, Int32, Int32)\n  fullName: XamlException.XamlException(String, Exception, Int32, Int32)\n  type: Constructor\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Initializes a new instance of the <xref href=\"System.Xaml.XamlException\"></xref> class. The instance contains a specified error message, inner exception, and line information.\n  syntax:\n    content: public XamlException (string message, Exception innerException, int lineNumber, int linePosition);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor must make sure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception.\n    - id: lineNumber\n      type: System.Int32\n      description: The line number to report to debugging or to line information consumers.\n    - id: linePosition\n      type: System.Int32\n      description: The line position to report to debugging or line information consumers.\n  overload: System.Xaml.XamlException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: XamlException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: XamlException.GetObjectData(SerializationInfo, StreamingContext)\n  type: Method\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Implements <xref href=\"System.Runtime.Serialization.ISerializable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\"></xref> and provides serialization support for the line information data.\n  syntax:\n    content: >-\n      [System.Security.SecurityCritical]\n\n      public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Xaml.XamlException.GetObjectData*\n  exceptions:\n  - type: System.ArgumentNullException\n    commentId: T:System.ArgumentNullException\n    description: <code>info</code> is `null`.\n  attributes:\n  - type: System.Security.SecurityCriticalAttribute\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.LineNumber\n  commentId: P:System.Xaml.XamlException.LineNumber\n  id: LineNumber\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: LineNumber\n  nameWithType: XamlException.LineNumber\n  fullName: XamlException.LineNumber\n  type: Property\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Gets or sets the line number component of XAML text line information that the exception reports.\n  syntax:\n    content: public int LineNumber { get; protected set; }\n    return:\n      type: System.Int32\n      description: The line number component of the XAML text line information.\n  overload: System.Xaml.XamlException.LineNumber*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.LinePosition\n  commentId: P:System.Xaml.XamlException.LinePosition\n  id: LinePosition\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: LinePosition\n  nameWithType: XamlException.LinePosition\n  fullName: XamlException.LinePosition\n  type: Property\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Gets or sets the line position component of XAML text line information that the exception reports.\n  syntax:\n    content: public int LinePosition { get; protected set; }\n    return:\n      type: System.Int32\n      description: The line position component of XAML text line information.\n  overload: System.Xaml.XamlException.LinePosition*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\n- uid: System.Xaml.XamlException.Message\n  commentId: P:System.Xaml.XamlException.Message\n  id: Message\n  parent: System.Xaml.XamlException\n  langs:\n  - csharp\n  name: Message\n  nameWithType: XamlException.Message\n  fullName: XamlException.Message\n  type: Property\n  assemblies:\n  - System.Xaml\n  namespace: System.Xaml\n  summary: Gets or sets the exception message, and if line information is available, appends the line information to the message.\n  remarks: <xref:System.Xaml.XamlException> overrides this property so that line information is directly included in the message and is therefore more easily visible for debuggers or other exception consumers. If line information is available, this property includes the line information. If line information is unavailable, the message is the same as the base message.\n  syntax:\n    content: public override string Message { get; }\n    return:\n      type: System.String\n      description: The exception message that includes the appended line information.\n  overload: System.Xaml.XamlException.Message*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n  ms.technology:\n  - dotnet-wpf\n  manager: martinek\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ArgumentNullException\n  parent: System\n  isExternal: false\n  name: ArgumentNullException\n  nameWithType: ArgumentNullException\n  fullName: System.ArgumentNullException\n- uid: System.Xaml.XamlException.#ctor\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException()\n  nameWithType: XamlException.XamlException()\n  fullName: XamlException.XamlException()\n- uid: System.Xaml.XamlException.#ctor(System.String)\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException(String)\n  nameWithType: XamlException.XamlException(String)\n  fullName: XamlException.XamlException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Xaml.XamlException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException(SerializationInfo, StreamingContext)\n  nameWithType: XamlException.XamlException(SerializationInfo, StreamingContext)\n  fullName: XamlException.XamlException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Xaml.XamlException.#ctor(System.String,System.Exception)\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException(String, Exception)\n  nameWithType: XamlException.XamlException(String, Exception)\n  fullName: XamlException.XamlException(String, Exception)\n- uid: System.Xaml.XamlException.#ctor(System.String,System.Exception,System.Int32,System.Int32)\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException(String, Exception, Int32, Int32)\n  nameWithType: XamlException.XamlException(String, Exception, Int32, Int32)\n  fullName: XamlException.XamlException(String, Exception, Int32, Int32)\n- uid: System.Int32\n  parent: System\n  isExternal: false\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Xaml.XamlException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: XamlException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: XamlException.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Xaml.XamlException.LineNumber\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: LineNumber\n  nameWithType: XamlException.LineNumber\n  fullName: XamlException.LineNumber\n- uid: System.Xaml.XamlException.LinePosition\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: LinePosition\n  nameWithType: XamlException.LinePosition\n  fullName: XamlException.LinePosition\n- uid: System.Xaml.XamlException.Message\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: Message\n  nameWithType: XamlException.Message\n  fullName: XamlException.Message\n- uid: System.Xaml.XamlException.#ctor*\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: XamlException\n  nameWithType: XamlException.XamlException\n  fullName: XamlException.XamlException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n- uid: System.Xaml.XamlException.GetObjectData*\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: XamlException.GetObjectData\n  fullName: XamlException.GetObjectData\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n- uid: System.Xaml.XamlException.LineNumber*\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: LineNumber\n  nameWithType: XamlException.LineNumber\n  fullName: XamlException.LineNumber\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n- uid: System.Xaml.XamlException.LinePosition*\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: LinePosition\n  nameWithType: XamlException.LinePosition\n  fullName: XamlException.LinePosition\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n- uid: System.Xaml.XamlException.Message*\n  parent: System.Xaml.XamlException\n  isExternal: false\n  name: Message\n  nameWithType: XamlException.Message\n  fullName: XamlException.Message\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Xaml/XamlException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}