{"nodes":[{"content":"Represents errors that occur during execution of WCF Data Services client applications.","nodes":[{"pos":[0,87],"content":"Represents errors that occur during execution of WCF Data Services client applications.","nodes":[{"content":"Represents errors that occur during execution of WCF Data Services client applications.","pos":[0,87]}]}],"pos":[1331,1419],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a system-supplied message that describes the error.","nodes":[{"pos":[0,172],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class with a system-supplied message that describes the error.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a system-supplied message that describes the error."}],"pos":[3484,3657],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,211],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.","pos":[0,211],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error.","pos":[0,151],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error."},{"content":"This message takes into account the current system culture.","pos":[152,211]}]}]},{"pos":[218,333],"content":"The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.InsufficientMemoryException&gt;</ph>.","pos":[0,115],"source":"The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>."}]},{"pos":[340,348],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[349,354],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[390,431],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[432,439],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[444,478],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[479,514],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[3668,4193],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified message that describes the error.","nodes":[{"pos":[0,166],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class with a specified message that describes the error.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified message that describes the error."}],"pos":[5645,5812],"yaml":true},{"content":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","nodes":[{"pos":[0,135],"content":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Data.Services.Client.DataServiceClientException&gt;</ph>.","pos":[0,135],"source":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>."}]},{"pos":[142,150],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[151,156],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[192,233],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[234,241],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[246,280],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[281,329],"content":"The error message string specified in <ph id=\"ph1\">`message`</ph>.","source":"The error message string specified in `message`."}],"pos":[5823,6161],"yaml":true,"extradata":"MT"},{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"pos":[0,162],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]}],"pos":[6315,6478],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,222],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[9927,10150],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|`null`.|  \n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|","nodes":[{"pos":[0,427],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id=\"ph2\">`null`</ph> if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,427],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[434,569],"content":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.Data.Services.Client.DataServiceClientException&gt;</ph>.","pos":[0,135],"source":"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>."}]},{"pos":[576,584],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[585,590],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[626,667],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[668,675],"content":"<ph id=\"ph1\">`null`</ph>.","source":"`null`."},{"pos":[680,714],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[715,763],"content":"The error message string specified in <ph id=\"ph1\">`message`</ph>.","source":"The error message string specified in `message`."}],"pos":[10161,10935],"yaml":true,"extradata":"MT"},{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"pos":[0,162],"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[0,162],"nodes":[{"content":"The message that describes the exception.","pos":[0,41]},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[42,162]}]}]}],"pos":[11115,11278],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,202],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not <ph id=\"ph2\">`null`</ph>, the current exception is raised in a <ph id=\"ph3\">`catch`</ph> block that handles the inner exception.","pos":[58,202],"source":" If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[11351,11554],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class.","nodes":[{"pos":[0,116],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class."}],"pos":[12986,13103],"yaml":true},{"content":"The string value that contains the error message.","nodes":[{"pos":[0,49],"content":"The string value that contains the error message.","nodes":[{"content":"The string value that contains the error message.","pos":[0,49]}]}],"pos":[13273,13323],"yaml":true},{"content":"The integer value that contains status code.","nodes":[{"pos":[0,44],"content":"The integer value that contains status code.","nodes":[{"content":"The integer value that contains status code.","pos":[0,44]}]}],"pos":[13388,13433],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class.","nodes":[{"pos":[0,116],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class."}],"pos":[14949,15066],"yaml":true},{"content":"The string value that contains the error message.","nodes":[{"pos":[0,49],"content":"The string value that contains the error message.","nodes":[{"content":"The string value that contains the error message.","pos":[0,49]}]}],"pos":[15262,15312],"yaml":true},{"content":"The `System.Exception` object that contains the inner exception.","nodes":[{"pos":[0,64],"content":"The <ph id=\"ph1\">`System.Exception`</ph> object that contains the inner exception.","source":"The `System.Exception` object that contains the inner exception."}],"pos":[15385,15450],"yaml":true},{"content":"The integer value that contains status code.","nodes":[{"pos":[0,44],"content":"The integer value that contains status code.","nodes":[{"content":"The integer value that contains status code.","pos":[0,44]}]}],"pos":[15515,15560],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with serialized data.","nodes":[{"pos":[0,137],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with serialized data."}],"pos":[17234,17372],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"pos":[0,231],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/docs/framework/serialization/xml-and-soap-serialization.md)</ept>.","pos":[114,231],"source":" For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)."}]}],"pos":[17383,17615],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[17943,17993],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[18088,18148],"yaml":true},{"content":"Gets the HTTP error status code returned after <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref>.","nodes":[{"pos":[0,123],"content":"Gets the HTTP error status code returned after <ph id=\"ph1\">&lt;xref href=\"System.Data.Services.Client.DataServiceClientException\"&gt;&lt;/xref&gt;</ph>.","source":"Gets the HTTP error status code returned after <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref>."}],"pos":[19487,19611],"yaml":true},{"content":"An integer value that represents the exception.","nodes":[{"pos":[0,47],"content":"An integer value that represents the exception.","nodes":[{"content":"An integer value that represents the exception.","pos":[0,47]}]}],"pos":[19721,19769],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Data.Services.Client.DataServiceClientException\n  commentId: T:System.Data.Services.Client.DataServiceClientException\n  id: DataServiceClientException\n  children:\n  - System.Data.Services.Client.DataServiceClientException.#ctor\n  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String)\n  - System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)\n  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)\n  - System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)\n  - System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Data.Services.Client.DataServiceClientException.StatusCode\n  langs:\n  - csharp\n  name: DataServiceClientException\n  nameWithType: DataServiceClientException\n  fullName: System.Data.Services.Client.DataServiceClientException\n  type: Class\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Represents errors that occur during execution of WCF Data Services client applications.\n  syntax:\n    content: 'public sealed class DataServiceClientException : InvalidOperationException'\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.InvalidOperationException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor\n  id: '#ctor'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException()\n  nameWithType: DataServiceClientException.DataServiceClientException()\n  fullName: DataServiceClientException.DataServiceClientException()\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a system-supplied message that describes the error.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.InsufficientMemoryException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public DataServiceClientException ();\n    parameters: []\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException(String)\n  nameWithType: DataServiceClientException.DataServiceClientException(String)\n  fullName: DataServiceClientException.DataServiceClientException(String)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified message that describes the error.\n  remarks: \"The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public DataServiceClientException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException(SerializationInfo, StreamingContext)\n  nameWithType: DataServiceClientException.DataServiceClientException(SerializationInfo, StreamingContext)\n  fullName: DataServiceClientException.DataServiceClientException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  syntax:\n    content: protected DataServiceClientException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: serializationInfo\n      type: System.Runtime.Serialization.SerializationInfo\n      description: ''\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: ''\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException(String, Exception)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Exception)\n  fullName: DataServiceClientException.DataServiceClientException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or `null` if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.Data.Services.Client.DataServiceClientException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string specified in `message`.|\"\n  syntax:\n    content: public DataServiceClientException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the exception. The caller of this constructor is required to ensure that this string has been localized for the current system culture.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not `null`, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)\n  id: '#ctor(System.String,System.Int32)'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException(String, Int32)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Int32)\n  fullName: DataServiceClientException.DataServiceClientException(String, Int32)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class.\n  syntax:\n    content: public DataServiceClientException (string message, int statusCode);\n    parameters:\n    - id: message\n      type: System.String\n      description: The string value that contains the error message.\n    - id: statusCode\n      type: System.Int32\n      description: The integer value that contains status code.\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)\n  id: '#ctor(System.String,System.Exception,System.Int32)'\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: DataServiceClientException(String, Exception, Int32)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Exception, Int32)\n  fullName: DataServiceClientException.DataServiceClientException(String, Exception, Int32)\n  type: Constructor\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class.\n  syntax:\n    content: public DataServiceClientException (string message, Exception innerException, int statusCode);\n    parameters:\n    - id: message\n      type: System.String\n      description: The string value that contains the error message.\n    - id: innerException\n      type: System.Exception\n      description: The `System.Exception` object that contains the inner exception.\n    - id: statusCode\n      type: System.Int32\n      description: The integer value that contains status code.\n  overload: System.Data.Services.Client.DataServiceClientException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: DataServiceClientException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: DataServiceClientException.GetObjectData(SerializationInfo, StreamingContext)\n  type: Method\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Initializes a new instance of the <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).\n  syntax:\n    content: >-\n      [System.Security.SecurityCritical]\n\n      public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.Data.Services.Client.DataServiceClientException.GetObjectData*\n  exceptions: []\n  attributes:\n  - type: System.Security.SecurityCriticalAttribute\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\n- uid: System.Data.Services.Client.DataServiceClientException.StatusCode\n  commentId: P:System.Data.Services.Client.DataServiceClientException.StatusCode\n  id: StatusCode\n  parent: System.Data.Services.Client.DataServiceClientException\n  langs:\n  - csharp\n  name: StatusCode\n  nameWithType: DataServiceClientException.StatusCode\n  fullName: DataServiceClientException.StatusCode\n  type: Property\n  assemblies:\n  - System.Data.Services.Client\n  namespace: System.Data.Services.Client\n  summary: Gets the HTTP error status code returned after <xref href=\"System.Data.Services.Client.DataServiceClientException\"></xref>.\n  syntax:\n    content: public int StatusCode { get; }\n    return:\n      type: System.Int32\n      description: An integer value that represents the exception.\n  overload: System.Data.Services.Client.DataServiceClientException.StatusCode*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n  ms.technology:\n  - dotnet-ado\n  author: JennieHubbard\n  ms.author: jhubbard\n  manager: jhubbard\nreferences:\n- uid: System.InvalidOperationException\n  parent: System\n  isExternal: false\n  name: InvalidOperationException\n  nameWithType: InvalidOperationException\n  fullName: System.InvalidOperationException\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException()\n  nameWithType: DataServiceClientException.DataServiceClientException()\n  fullName: DataServiceClientException.DataServiceClientException()\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException(String)\n  nameWithType: DataServiceClientException.DataServiceClientException(String)\n  fullName: DataServiceClientException.DataServiceClientException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException(SerializationInfo, StreamingContext)\n  nameWithType: DataServiceClientException.DataServiceClientException(SerializationInfo, StreamingContext)\n  fullName: DataServiceClientException.DataServiceClientException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException(String, Exception)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Exception)\n  fullName: DataServiceClientException.DataServiceClientException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Int32)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException(String, Int32)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Int32)\n  fullName: DataServiceClientException.DataServiceClientException(String, Int32)\n- uid: System.Int32\n  parent: System\n  isExternal: false\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor(System.String,System.Exception,System.Int32)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException(String, Exception, Int32)\n  nameWithType: DataServiceClientException.DataServiceClientException(String, Exception, Int32)\n  fullName: DataServiceClientException.DataServiceClientException(String, Exception, Int32)\n- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: DataServiceClientException.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: DataServiceClientException.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Data.Services.Client.DataServiceClientException.StatusCode\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: StatusCode\n  nameWithType: DataServiceClientException.StatusCode\n  fullName: DataServiceClientException.StatusCode\n- uid: System.Data.Services.Client.DataServiceClientException.#ctor*\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: DataServiceClientException\n  nameWithType: DataServiceClientException.DataServiceClientException\n  fullName: DataServiceClientException.DataServiceClientException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n- uid: System.Data.Services.Client.DataServiceClientException.GetObjectData*\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: DataServiceClientException.GetObjectData\n  fullName: DataServiceClientException.GetObjectData\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n- uid: System.Data.Services.Client.DataServiceClientException.StatusCode*\n  parent: System.Data.Services.Client.DataServiceClientException\n  isExternal: false\n  name: StatusCode\n  nameWithType: DataServiceClientException.StatusCode\n  fullName: DataServiceClientException.StatusCode\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Data.Services.Client/DataServiceClientException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}