{"nodes":[{"content":"Represents errors that occur when a <xref href=\"System.Web.UI.WebControls.LinqDataSource\"></xref> control parses values to create a query.","nodes":[{"pos":[0,138],"content":"Represents errors that occur when a <ph id=\"ph1\">&lt;xref href=\"System.Web.UI.WebControls.LinqDataSource\"&gt;&lt;/xref&gt;</ph> control parses values to create a query.","source":"Represents errors that occur when a <xref href=\"System.Web.UI.WebControls.LinqDataSource\"></xref> control parses values to create a query."}],"pos":[584,723],"yaml":true},{"content":"The <xref:System.Web.Query.Dynamic.ParseException> object contains information about exceptions that occur when the <xref:System.Web.UI.WebControls.LinqDataSource> control parses values in order to dynamically create a query.  \n  \n If the <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> property includes a property that is not in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the property does not exist in the data object.  \n  \n You can assign the data object in the <xref:System.Web.UI.WebControls.LinqDataSource.Selecting> event by setting the <xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A> property to an object that is returned from a query. If you select a property that does not exist in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the particular property does not exist in an `AnonymousType` object.","nodes":[{"pos":[0,225],"content":"The <xref:System.Web.Query.Dynamic.ParseException> object contains information about exceptions that occur when the <xref:System.Web.UI.WebControls.LinqDataSource> control parses values in order to dynamically create a query.","nodes":[{"content":"The <ph id=\"ph1\">&lt;xref:System.Web.Query.Dynamic.ParseException&gt;</ph> object contains information about exceptions that occur when the <ph id=\"ph2\">&lt;xref:System.Web.UI.WebControls.LinqDataSource&gt;</ph> control parses values in order to dynamically create a query.","pos":[0,225],"source":"The <xref:System.Web.Query.Dynamic.ParseException> object contains information about exceptions that occur when the <xref:System.Web.UI.WebControls.LinqDataSource> control parses values in order to dynamically create a query."}]},{"pos":[232,559],"content":"If the <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> property includes a property that is not in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the property does not exist in the data object.","nodes":[{"content":"If the <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> property includes a property that is not in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the property does not exist in the data object.","pos":[0,327],"nodes":[{"content":"If the <ph id=\"ph1\">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Select%2A&gt;</ph> property includes a property that is not in the data object, the <ph id=\"ph2\">&lt;xref:System.Web.UI.WebControls.LinqDataSource&gt;</ph> control raises a <ph id=\"ph3\">&lt;xref:System.Web.Query.Dynamic.ParseException&gt;</ph> exception.","pos":[0,252],"source":"If the <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> property includes a property that is not in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception."},{"content":"The message indicates that the property does not exist in the data object.","pos":[253,327]}]}]},{"pos":[566,1096],"content":"You can assign the data object in the <xref:System.Web.UI.WebControls.LinqDataSource.Selecting> event by setting the <xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A> property to an object that is returned from a query. If you select a property that does not exist in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the particular property does not exist in an `AnonymousType` object.","nodes":[{"content":"You can assign the data object in the <ph id=\"ph1\">&lt;xref:System.Web.UI.WebControls.LinqDataSource.Selecting&gt;</ph> event by setting the <ph id=\"ph2\">&lt;xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A&gt;</ph> property to an object that is returned from a query.","pos":[0,242],"source":"You can assign the data object in the <xref:System.Web.UI.WebControls.LinqDataSource.Selecting> event by setting the <xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A> property to an object that is returned from a query."},{"content":"If you select a property that does not exist in the data object, the <ph id=\"ph1\">&lt;xref:System.Web.UI.WebControls.LinqDataSource&gt;</ph> control raises a <ph id=\"ph2\">&lt;xref:System.Web.Query.Dynamic.ParseException&gt;</ph> exception.","pos":[243,434],"source":" If you select a property that does not exist in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception."},{"content":"The message indicates that the particular property does not exist in an <ph id=\"ph1\">`AnonymousType`</ph> object.","pos":[435,530],"source":" The message indicates that the particular property does not exist in an `AnonymousType` object."}]}],"pos":[734,1837],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.Web.Query.Dynamic.ParseException\"></xref> class.","nodes":[{"pos":[0,101],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.Web.Query.Dynamic.ParseException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.Web.Query.Dynamic.ParseException\"></xref> class."}],"pos":[3782,3884],"yaml":true},{"content":"The message that describes the error.","nodes":[{"pos":[0,37],"content":"The message that describes the error.","nodes":[{"content":"The message that describes the error.","pos":[0,37]}]}],"pos":[4040,4078],"yaml":true},{"content":"The location of the error.","nodes":[{"pos":[0,26],"content":"The location of the error.","nodes":[{"content":"The location of the error.","pos":[0,26]}]}],"pos":[4141,4168],"yaml":true},{"content":"Gets the location of the error.","nodes":[{"pos":[0,31],"content":"Gets the location of the error.","nodes":[{"content":"Gets the location of the error.","pos":[0,31]}]}],"pos":[5189,5221],"yaml":true},{"content":"The location where the exception occurred.","nodes":[{"pos":[0,42],"content":"The location where the exception occurred.","nodes":[{"content":"The location where the exception occurred.","pos":[0,42]}]}],"pos":[5329,5372],"yaml":true},{"content":"Returns the error message and the location of the error.","nodes":[{"pos":[0,56],"content":"Returns the error message and the location of the error.","nodes":[{"content":"Returns the error message and the location of the error.","pos":[0,56]}]}],"pos":[6400,6457],"yaml":true},{"content":"The message and the position of the error.","nodes":[{"pos":[0,42],"content":"The message and the position of the error.","nodes":[{"content":"The message and the position of the error.","pos":[0,42]}]}],"pos":[6592,6635],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Web.Query.Dynamic.ParseException\n  commentId: T:System.Web.Query.Dynamic.ParseException\n  id: ParseException\n  children:\n  - System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)\n  - System.Web.Query.Dynamic.ParseException.Position\n  - System.Web.Query.Dynamic.ParseException.ToString\n  langs:\n  - csharp\n  name: ParseException\n  nameWithType: ParseException\n  fullName: System.Web.Query.Dynamic.ParseException\n  type: Class\n  assemblies:\n  - System.Web.Extensions\n  namespace: System.Web.Query.Dynamic\n  summary: Represents errors that occur when a <xref href=\"System.Web.UI.WebControls.LinqDataSource\"></xref> control parses values to create a query.\n  remarks: \"The <xref:System.Web.Query.Dynamic.ParseException> object contains information about exceptions that occur when the <xref:System.Web.UI.WebControls.LinqDataSource> control parses values in order to dynamically create a query.  \\n  \\n If the <xref:System.Web.UI.WebControls.LinqDataSource.Select%2A> property includes a property that is not in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the property does not exist in the data object.  \\n  \\n You can assign the data object in the <xref:System.Web.UI.WebControls.LinqDataSource.Selecting> event by setting the <xref:System.Web.UI.WebControls.LinqDataSourceSelectEventArgs.Result%2A> property to an object that is returned from a query. If you select a property that does not exist in the data object, the <xref:System.Web.UI.WebControls.LinqDataSource> control raises a <xref:System.Web.Query.Dynamic.ParseException> exception. The message indicates that the particular property does not exist in an `AnonymousType` object.\"\n  syntax:\n    content: 'public class ParseException : Exception'\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n  ms.technology:\n  - dotnet-webforms\n  author: tdykstra\n  ms.author: tdykstra\n  manager: wpickett\n- uid: System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)\n  commentId: M:System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)\n  id: '#ctor(System.String,System.Int32)'\n  parent: System.Web.Query.Dynamic.ParseException\n  langs:\n  - csharp\n  name: ParseException(String, Int32)\n  nameWithType: ParseException.ParseException(String, Int32)\n  fullName: ParseException.ParseException(String, Int32)\n  type: Constructor\n  assemblies:\n  - System.Web.Extensions\n  namespace: System.Web.Query.Dynamic\n  summary: Initializes a new instance of the <xref href=\"System.Web.Query.Dynamic.ParseException\"></xref> class.\n  syntax:\n    content: public ParseException (string message, int position);\n    parameters:\n    - id: message\n      type: System.String\n      description: The message that describes the error.\n    - id: position\n      type: System.Int32\n      description: The location of the error.\n  overload: System.Web.Query.Dynamic.ParseException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n  ms.technology:\n  - dotnet-webforms\n  author: tdykstra\n  ms.author: tdykstra\n  manager: wpickett\n- uid: System.Web.Query.Dynamic.ParseException.Position\n  commentId: P:System.Web.Query.Dynamic.ParseException.Position\n  id: Position\n  parent: System.Web.Query.Dynamic.ParseException\n  langs:\n  - csharp\n  name: Position\n  nameWithType: ParseException.Position\n  fullName: ParseException.Position\n  type: Property\n  assemblies:\n  - System.Web.Extensions\n  namespace: System.Web.Query.Dynamic\n  summary: Gets the location of the error.\n  syntax:\n    content: public int Position { get; }\n    return:\n      type: System.Int32\n      description: The location where the exception occurred.\n  overload: System.Web.Query.Dynamic.ParseException.Position*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n  ms.technology:\n  - dotnet-webforms\n  author: tdykstra\n  ms.author: tdykstra\n  manager: wpickett\n- uid: System.Web.Query.Dynamic.ParseException.ToString\n  commentId: M:System.Web.Query.Dynamic.ParseException.ToString\n  id: ToString\n  parent: System.Web.Query.Dynamic.ParseException\n  langs:\n  - csharp\n  name: ToString()\n  nameWithType: ParseException.ToString()\n  fullName: ParseException.ToString()\n  type: Method\n  assemblies:\n  - System.Web.Extensions\n  namespace: System.Web.Query.Dynamic\n  summary: Returns the error message and the location of the error.\n  syntax:\n    content: public override string ToString ();\n    parameters: []\n    return:\n      type: System.String\n      description: The message and the position of the error.\n  overload: System.Web.Query.Dynamic.ParseException.ToString*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n  ms.technology:\n  - dotnet-webforms\n  author: tdykstra\n  ms.author: tdykstra\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Web.Query.Dynamic.ParseException.#ctor(System.String,System.Int32)\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: ParseException(String, Int32)\n  nameWithType: ParseException.ParseException(String, Int32)\n  fullName: ParseException.ParseException(String, Int32)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Int32\n  parent: System\n  isExternal: false\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Web.Query.Dynamic.ParseException.Position\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: Position\n  nameWithType: ParseException.Position\n  fullName: ParseException.Position\n- uid: System.Web.Query.Dynamic.ParseException.ToString\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: ToString()\n  nameWithType: ParseException.ToString()\n  fullName: ParseException.ToString()\n- uid: System.Web.Query.Dynamic.ParseException.#ctor*\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: ParseException\n  nameWithType: ParseException.ParseException\n  fullName: ParseException.ParseException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n- uid: System.Web.Query.Dynamic.ParseException.Position*\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: Position\n  nameWithType: ParseException.Position\n  fullName: ParseException.Position\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n- uid: System.Web.Query.Dynamic.ParseException.ToString*\n  parent: System.Web.Query.Dynamic.ParseException\n  isExternal: false\n  name: ToString\n  nameWithType: ParseException.ToString\n  fullName: ParseException.ToString\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.Web.Query.Dynamic/ParseException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}