{"nodes":[{"content":"Thrown when an error occurs within a named pipe.","nodes":[{"pos":[0,48],"content":"Thrown when an error occurs within a named pipe.","nodes":[{"content":"Thrown when an error occurs within a named pipe.","pos":[0,48]}]}],"pos":[709,758],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class.","nodes":[{"pos":[0,85],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.IO.PipeException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class."}],"pos":[2555,2641],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message.","nodes":[{"pos":[0,116],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.IO.PipeException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message."}],"pos":[3704,3821],"yaml":true},{"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"pos":[0,84],"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"content":"A string that contains the error message that explains the reason for the exception.","pos":[0,84]}]}],"pos":[3962,4047],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified serialization information and streaming context.","nodes":[{"pos":[0,152],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.IO.PipeException\"&gt;&lt;/xref&gt;</ph> class with the specified serialization information and streaming context.","source":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified serialization information and streaming context."}],"pos":[5367,5520],"yaml":true},{"content":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that contains all the data required to serialize the exception.","nodes":[{"pos":[0,135],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;&lt;/xref&gt;</ph> that contains all the data required to serialize the exception.","source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that contains all the data required to serialize the exception."}],"pos":[5786,5922],"yaml":true},{"content":"The <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that specifies the source and destination of the stream.","nodes":[{"pos":[0,127],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Runtime.Serialization.StreamingContext\"&gt;&lt;/xref&gt;</ph> that specifies the source and destination of the stream.","source":"The <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that specifies the source and destination of the stream."}],"pos":[6017,6145],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified error message and the inner exception.","nodes":[{"pos":[0,142],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.IO.PipeException\"&gt;&lt;/xref&gt;</ph> class with the specified error message and the inner exception.","source":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified error message and the inner exception."}],"pos":[7225,7368],"yaml":true},{"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"pos":[0,84],"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"content":"A string that contains the error message that explains the reason for the exception.","pos":[0,84]}]}],"pos":[7526,7611],"yaml":true},{"content":"The <xref href=\"System.Exception\"></xref> that caused the current exception to be thrown.","nodes":[{"pos":[0,89],"content":"The <ph id=\"ph1\">&lt;xref href=\"System.Exception\"&gt;&lt;/xref&gt;</ph> that caused the current exception to be thrown.","source":"The <xref href=\"System.Exception\"></xref> that caused the current exception to be thrown."}],"pos":[7675,7765],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message and error code.","nodes":[{"pos":[0,131],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.IO.PipeException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and error code.","source":"Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message and error code."}],"pos":[8821,8953],"yaml":true},{"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"pos":[0,84],"content":"A string that contains the error message that explains the reason for the exception.","nodes":[{"content":"A string that contains the error message that explains the reason for the exception.","pos":[0,84]}]}],"pos":[9109,9194],"yaml":true},{"content":"An integer that contains the error code.","nodes":[{"pos":[0,40],"content":"An integer that contains the error code.","nodes":[{"content":"An integer that contains the error code.","pos":[0,40]}]}],"pos":[9258,9299],"yaml":true},{"content":"Gets the error code to be returned with the exception.","nodes":[{"pos":[0,54],"content":"Gets the error code to be returned with the exception.","nodes":[{"content":"Gets the error code to be returned with the exception.","pos":[0,54]}]}],"pos":[10221,10276],"yaml":true},{"content":"An integer with the error code to be returned with the exception.","nodes":[{"pos":[0,65],"content":"An integer with the error code to be returned with the exception.","nodes":[{"content":"An integer with the error code to be returned with the exception.","pos":[0,65]}]}],"pos":[10393,10459],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.IO.PipeException\n  commentId: T:System.IO.PipeException\n  id: PipeException\n  children:\n  - System.IO.PipeException.#ctor\n  - System.IO.PipeException.#ctor(System.String)\n  - System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.IO.PipeException.#ctor(System.String,System.Exception)\n  - System.IO.PipeException.#ctor(System.String,System.Int32)\n  - System.IO.PipeException.ErrorCode\n  langs:\n  - csharp\n  name: PipeException\n  nameWithType: PipeException\n  fullName: System.IO.PipeException\n  type: Class\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Thrown when an error occurs within a named pipe.\n  syntax:\n    content: 'public class PipeException : System.IO.IOException'\n  inheritance:\n  - System.Object\n  - System.Exception\n  - System.IO.IOException\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.#ctor\n  commentId: M:System.IO.PipeException.#ctor\n  id: '#ctor'\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: PipeException()\n  nameWithType: PipeException.PipeException()\n  fullName: PipeException.PipeException()\n  type: Constructor\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class.\n  syntax:\n    content: public PipeException ();\n    parameters: []\n  overload: System.IO.PipeException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.#ctor(System.String)\n  commentId: M:System.IO.PipeException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: PipeException(String)\n  nameWithType: PipeException.PipeException(String)\n  fullName: PipeException.PipeException(String)\n  type: Constructor\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message.\n  syntax:\n    content: public PipeException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A string that contains the error message that explains the reason for the exception.\n  overload: System.IO.PipeException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: PipeException(SerializationInfo, StreamingContext)\n  nameWithType: PipeException.PipeException(SerializationInfo, StreamingContext)\n  fullName: PipeException.PipeException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified serialization information and streaming context.\n  syntax:\n    content: protected PipeException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that contains all the data required to serialize the exception.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref href=\"System.Runtime.Serialization.StreamingContext\"></xref> that specifies the source and destination of the stream.\n  overload: System.IO.PipeException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.#ctor(System.String,System.Exception)\n  commentId: M:System.IO.PipeException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: PipeException(String, Exception)\n  nameWithType: PipeException.PipeException(String, Exception)\n  fullName: PipeException.PipeException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with the specified error message and the inner exception.\n  syntax:\n    content: public PipeException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: A string that contains the error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The <xref href=\"System.Exception\"></xref> that caused the current exception to be thrown.\n  overload: System.IO.PipeException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.#ctor(System.String,System.Int32)\n  commentId: M:System.IO.PipeException.#ctor(System.String,System.Int32)\n  id: '#ctor(System.String,System.Int32)'\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: PipeException(String, Int32)\n  nameWithType: PipeException.PipeException(String, Int32)\n  fullName: PipeException.PipeException(String, Int32)\n  type: Constructor\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Initializes a new instance of the <xref href=\"System.IO.PipeException\"></xref> class with a specified error message and error code.\n  syntax:\n    content: public PipeException (string message, int errorCode);\n    parameters:\n    - id: message\n      type: System.String\n      description: A string that contains the error message that explains the reason for the exception.\n    - id: errorCode\n      type: System.Int32\n      description: An integer that contains the error code.\n  overload: System.IO.PipeException.#ctor*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\n- uid: System.IO.PipeException.ErrorCode\n  commentId: P:System.IO.PipeException.ErrorCode\n  id: ErrorCode\n  parent: System.IO.PipeException\n  langs:\n  - csharp\n  name: ErrorCode\n  nameWithType: PipeException.ErrorCode\n  fullName: PipeException.ErrorCode\n  type: Property\n  assemblies:\n  - System.ServiceModel\n  namespace: System.IO\n  summary: Gets the error code to be returned with the exception.\n  syntax:\n    content: public virtual int ErrorCode { get; }\n    return:\n      type: System.Int32\n      description: An integer with the error code to be returned with the exception.\n  overload: System.IO.PipeException.ErrorCode*\n  exceptions: []\n  version:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n  ms.technology:\n  - dotnet-standard\n  author: Erikre\n  ms.author: erikre\n  manager: erikre\nreferences:\n- uid: System.IO.IOException\n  parent: System.IO\n  isExternal: false\n  name: IOException\n  nameWithType: IOException\n  fullName: System.IO.IOException\n- uid: System.IO.PipeException.#ctor\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException()\n  nameWithType: PipeException.PipeException()\n  fullName: PipeException.PipeException()\n- uid: System.IO.PipeException.#ctor(System.String)\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException(String)\n  nameWithType: PipeException.PipeException(String)\n  fullName: PipeException.PipeException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.IO.PipeException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException(SerializationInfo, StreamingContext)\n  nameWithType: PipeException.PipeException(SerializationInfo, StreamingContext)\n  fullName: PipeException.PipeException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.IO.PipeException.#ctor(System.String,System.Exception)\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException(String, Exception)\n  nameWithType: PipeException.PipeException(String, Exception)\n  fullName: PipeException.PipeException(String, Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.IO.PipeException.#ctor(System.String,System.Int32)\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException(String, Int32)\n  nameWithType: PipeException.PipeException(String, Int32)\n  fullName: PipeException.PipeException(String, Int32)\n- uid: System.Int32\n  parent: System\n  isExternal: false\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.IO.PipeException.ErrorCode\n  parent: System.IO.PipeException\n  isExternal: false\n  name: ErrorCode\n  nameWithType: PipeException.ErrorCode\n  fullName: PipeException.ErrorCode\n- uid: System.IO.PipeException.#ctor*\n  parent: System.IO.PipeException\n  isExternal: false\n  name: PipeException\n  nameWithType: PipeException.PipeException\n  fullName: PipeException.PipeException\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n- uid: System.IO.PipeException.ErrorCode*\n  parent: System.IO.PipeException\n  isExternal: false\n  name: ErrorCode\n  nameWithType: PipeException.ErrorCode\n  fullName: PipeException.ErrorCode\n  monikers:\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System.IO/PipeException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}