{"nodes":[{"content":"The exception that is thrown when an attempt is made to store an element of the wrong type within an array.","nodes":[{"pos":[0,107],"content":"The exception that is thrown when an attempt is made to store an element of the wrong type within an array.","nodes":[{"content":"The exception that is thrown when an attempt is made to store an element of the wrong type within an array.","pos":[0,107]}]}],"pos":[739,847],"yaml":true},{"content":"<xref:System.ArrayTypeMismatchException> is thrown when the system cannot convert the element to the type declared for the array. For example, an element of type <xref:System.String> cannot be stored in an <xref:System.Int32> array because conversion between these types is not supported. It is generally unnecessary for applications to throw this exception.  \n  \n The following Microsoft intermediate language (MSIL) instructions throw <xref:System.ArrayTypeMismatchException> :  \n  \n-   ldelem.\\<type>  \n  \n-   ldelema  \n  \n-   stelem.\\<type>  \n  \n <xref:System.ArrayTypeMismatchException> uses the HRESULT COR_E_ARRAYTYPEMISMATCH, which has the value 0x80131503.  \n  \n For a list of initial property values for an instance of <xref:System.ArrayTypeMismatchException>, see the <xref:System.ArrayTypeMismatchException> constructors.","nodes":[{"pos":[0,358],"content":"<xref:System.ArrayTypeMismatchException> is thrown when the system cannot convert the element to the type declared for the array. For example, an element of type <xref:System.String> cannot be stored in an <xref:System.Int32> array because conversion between these types is not supported. It is generally unnecessary for applications to throw this exception.","nodes":[{"content":"<xref:System.ArrayTypeMismatchException> is thrown when the system cannot convert the element to the type declared for the array. For example, an element of type <xref:System.String> cannot be stored in an <xref:System.Int32> array because conversion between these types is not supported. It is generally unnecessary for applications to throw this exception.","pos":[0,358],"nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph> is thrown when the system cannot convert the element to the type declared for the array.","pos":[0,129],"source":"<xref:System.ArrayTypeMismatchException> is thrown when the system cannot convert the element to the type declared for the array."},{"content":"For example, an element of type <ph id=\"ph1\">&lt;xref:System.String&gt;</ph> cannot be stored in an <ph id=\"ph2\">&lt;xref:System.Int32&gt;</ph> array because conversion between these types is not supported.","pos":[130,288],"source":" For example, an element of type <xref:System.String> cannot be stored in an <xref:System.Int32> array because conversion between these types is not supported."},{"content":"It is generally unnecessary for applications to throw this exception.","pos":[289,358]}]}]},{"pos":[365,479],"content":"The following Microsoft intermediate language (MSIL) instructions throw <xref:System.ArrayTypeMismatchException> :","nodes":[{"content":"The following Microsoft intermediate language (MSIL) instructions throw <ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph> :","pos":[0,114],"source":"The following Microsoft intermediate language (MSIL) instructions throw <xref:System.ArrayTypeMismatchException> :"}]},{"pos":[489,503],"content":"ldelem.\\<type>","nodes":[{"content":"ldelem.<ph id=\"ph1\">\\&lt;</ph>type&gt;","pos":[0,14],"source":"ldelem.\\<type>"}]},{"pos":[513,520],"content":"ldelema","nodes":[{"content":"ldelema","pos":[0,7]}]},{"pos":[530,544],"content":"stelem.\\<type>","nodes":[{"content":"stelem.<ph id=\"ph1\">\\&lt;</ph>type&gt;","pos":[0,14],"source":"stelem.\\<type>"}]},{"pos":[551,665],"content":"<xref:System.ArrayTypeMismatchException> uses the HRESULT COR_E_ARRAYTYPEMISMATCH, which has the value 0x80131503.","nodes":[{"content":"<ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph> uses the HRESULT COR_E_ARRAYTYPEMISMATCH, which has the value 0x80131503.","pos":[0,114],"source":"<xref:System.ArrayTypeMismatchException> uses the HRESULT COR_E_ARRAYTYPEMISMATCH, which has the value 0x80131503."}]},{"pos":[672,833],"content":"For a list of initial property values for an instance of <xref:System.ArrayTypeMismatchException>, see the <xref:System.ArrayTypeMismatchException> constructors.","nodes":[{"content":"For a list of initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph>, see the <ph id=\"ph2\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph> constructors.","pos":[0,161],"source":"For a list of initial property values for an instance of <xref:System.ArrayTypeMismatchException>, see the <xref:System.ArrayTypeMismatchException> constructors."}]}],"pos":[858,1708],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class.","nodes":[{"pos":[0,95],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArrayTypeMismatchException\"&gt;&lt;/xref&gt;</ph> class.","source":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class."}],"pos":[4829,4925],"yaml":true},{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Source array type cannot be assigned to destination array type.\" This message takes into account the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The localized error message string.|","nodes":[{"pos":[0,285],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Source array type cannot be assigned to destination array type.\" This message takes into account the current system culture.","nodes":[{"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Source array type cannot be assigned to destination array type.\" This message takes into account the current system culture.","pos":[0,285],"nodes":[{"content":"This constructor initializes the <ph id=\"ph1\">&lt;xref:System.Exception.Message%2A&gt;</ph> property of the new instance to a system-supplied message that describes the error, such as \"Source array type cannot be assigned to destination array type.\"","pos":[0,225],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \"Source array type cannot be assigned to destination array type.\""},{"content":"This message takes into account the current system culture.","pos":[226,285]}]}]},{"pos":[292,406],"content":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>."}]},{"pos":[413,421],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[422,427],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[463,504],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[505,550],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[555,589],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[590,625],"content":"The localized error message string.","nodes":[{"content":"The localized error message string.","pos":[0,35]}]}],"pos":[4936,5574],"yaml":true,"extradata":"MT"},{"content":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message.","nodes":[{"pos":[0,126],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArrayTypeMismatchException\"&gt;&lt;/xref&gt;</ph> class with a specified error message.","source":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message."}],"pos":[8227,8354],"yaml":true},{"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \n  \n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,199],"content":"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.","nodes":[{"content":"The content of the <ph id=\"ph1\">`message`</ph> parameter is intended to be understood by humans.","pos":[0,78],"source":"The content of the `message` parameter is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[79,199]}]},{"pos":[206,320],"content":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>."}]},{"pos":[327,335],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[336,341],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[377,418],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[419,464],"content":"A null reference (<ph id=\"ph1\">`Nothing`</ph> in Visual Basic).","source":"A null reference (`Nothing` in Visual Basic)."},{"pos":[469,503],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[504,529],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[8365,8905],"yaml":true,"extradata":"MT"},{"content":"A <xref href=\"System.String\"></xref> that describes the error.","nodes":[{"pos":[0,62],"content":"A <ph id=\"ph1\">&lt;xref href=\"System.String\"&gt;&lt;/xref&gt;</ph> that describes the error.","source":"A <xref href=\"System.String\"></xref> that describes the error."}],"pos":[9961,10024],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with serialized data.","nodes":[{"pos":[0,116],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArrayTypeMismatchException\"&gt;&lt;/xref&gt;</ph> class with serialized data.","source":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with serialized data."}],"pos":[12025,12142],"yaml":true},{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"pos":[0,231],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/docs/framework/serialization/xml-and-soap-serialization.md)</ept>.","pos":[114,231],"source":" For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md)."}]}],"pos":[12153,12385],"yaml":true,"extradata":"MT"},{"content":"The object that holds the serialized object data.","nodes":[{"pos":[0,49],"content":"The object that holds the serialized object data.","nodes":[{"content":"The object that holds the serialized object data.","pos":[0,49]}]}],"pos":[12664,12714],"yaml":true},{"content":"The contextual information about the source or destination.","nodes":[{"pos":[0,59],"content":"The contextual information about the source or destination.","nodes":[{"content":"The contextual information about the source or destination.","pos":[0,59]}]}],"pos":[12809,12869],"yaml":true},{"content":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.","nodes":[{"pos":[0,201],"content":"Initializes a new instance of the <ph id=\"ph1\">&lt;xref href=\"System.ArrayTypeMismatchException\"&gt;&lt;/xref&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.","source":"Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."}],"pos":[14286,14488],"yaml":true},{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \n  \n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \n  \n|Property|Value|  \n|--------------|-----------|  \n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \n|<xref:System.Exception.Message%2A>|The error message string.|","nodes":[{"pos":[0,465],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The <ph id=\"ph1\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or a null reference (<ph id=\"ph2\">`Nothing`</ph> in Visual Basic) if the <ph id=\"ph3\">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.","pos":[183,465],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor."}]},{"pos":[472,586],"content":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.","nodes":[{"content":"The following table shows the initial property values for an instance of <ph id=\"ph1\">&lt;xref:System.ArrayTypeMismatchException&gt;</ph>.","pos":[0,114],"source":"The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>."}]},{"pos":[593,601],"content":"Property","nodes":[{"content":"Property","pos":[0,8]}]},{"pos":[602,607],"content":"Value","nodes":[{"content":"Value","pos":[0,5]}]},{"pos":[643,684],"content":"<xref:System.Exception.InnerException%2A>","nodes":[]},{"pos":[685,715],"content":"The inner exception reference.","nodes":[{"content":"The inner exception reference.","pos":[0,30]}]},{"pos":[720,754],"content":"<xref:System.Exception.Message%2A>","nodes":[]},{"pos":[755,780],"content":"The error message string.","nodes":[{"content":"The error message string.","pos":[0,25]}]}],"pos":[14499,15290],"yaml":true,"extradata":"MT"},{"content":"The error message that explains the reason for the exception.","nodes":[{"pos":[0,61],"content":"The error message that explains the reason for the exception.","nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]}],"pos":[16393,16455],"yaml":true},{"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"pos":[0,212],"content":"The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.","nodes":[{"content":"The exception that is the cause of the current exception.","pos":[0,57]},{"content":"If the <bpt id=\"p1\">&lt;code&gt;</bpt><ph id=\"ph1\">innerException</ph><ept id=\"p1\">&lt;/code&gt;</ept> parameter is not a null reference, the current exception is raised in a <ph id=\"ph2\">`catch`</ph> block that handles the inner exception.","pos":[58,212],"source":" If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception."}]}],"pos":[16528,16741],"yaml":true}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.ArrayTypeMismatchException\n  commentId: T:System.ArrayTypeMismatchException\n  id: ArrayTypeMismatchException\n  children:\n  - System.ArrayTypeMismatchException.#ctor\n  - System.ArrayTypeMismatchException.#ctor(System.String)\n  - System.ArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.ArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: ArrayTypeMismatchException\n  nameWithType: ArrayTypeMismatchException\n  fullName: System.ArrayTypeMismatchException\n  type: Class\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: The exception that is thrown when an attempt is made to store an element of the wrong type within an array.\n  remarks: \"<xref:System.ArrayTypeMismatchException> is thrown when the system cannot convert the element to the type declared for the array. For example, an element of type <xref:System.String> cannot be stored in an <xref:System.Int32> array because conversion between these types is not supported. It is generally unnecessary for applications to throw this exception.  \\n  \\n The following Microsoft intermediate language (MSIL) instructions throw <xref:System.ArrayTypeMismatchException> :  \\n  \\n-   ldelem.\\\\<type>  \\n  \\n-   ldelema  \\n  \\n-   stelem.\\\\<type>  \\n  \\n <xref:System.ArrayTypeMismatchException> uses the HRESULT COR_E_ARRAYTYPEMISMATCH, which has the value 0x80131503.  \\n  \\n For a list of initial property values for an instance of <xref:System.ArrayTypeMismatchException>, see the <xref:System.ArrayTypeMismatchException> constructors.\"\n  example:\n  - \"The following code example demonstrates scenarios where <xref:System.ArrayTypeMismatchException> is thrown.  \\n  \\n [!code-cpp[System.ArrayTypeMismatch#1](~/samples/snippets/cpp/VS_Snippets_CLR_System/system.ArrayTypeMismatch/CPP/class1.cpp#1)]\\n [!code-csharp[System.ArrayTypeMismatch#1](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.ArrayTypeMismatch/CS/class1.cs#1)]\\n [!code-vb[System.ArrayTypeMismatch#1](~/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.ArrayTypeMismatch/VB/class1.vb#1)]\"\n  syntax:\n    content: >-\n      [System.Runtime.InteropServices.ComVisible(true)]\n\n      public class ArrayTypeMismatchException : SystemException\n  inheritance:\n  - System.Object\n  - System.Exception\n  implements: []\n  inheritedMembers:\n  - System.Exception.Data\n  - System.Exception.GetBaseException\n  - System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Exception.GetType\n  - System.Exception.HelpLink\n  - System.Exception.HResult\n  - System.Exception.InnerException\n  - System.Exception.Message\n  - System.Exception.SerializeObjectState\n  - System.Exception.Source\n  - System.Exception.StackTrace\n  - System.Exception.TargetSite\n  - System.Exception.ToString\n  - System.Object.Equals(System.Object)\n  - System.Object.Equals(System.Object,System.Object)\n  - System.Object.GetHashCode\n  - System.Object.MemberwiseClone\n  - System.Object.ReferenceEquals(System.Object,System.Object)\n  attributes:\n  - type: System.Runtime.InteropServices.ComVisibleAttribute\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArrayTypeMismatchException.#ctor\n  commentId: M:System.ArrayTypeMismatchException.#ctor\n  id: '#ctor'\n  parent: System.ArrayTypeMismatchException\n  langs:\n  - csharp\n  name: ArrayTypeMismatchException()\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException()\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException()\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error, such as \\\"Source array type cannot be assigned to destination array type.\\\" This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  example:\n  - \"The following example demonstrates the ArrayTypeMismatchException() constructor of the <xref:System.ArrayTypeMismatchException> class. It contains a function which takes two arrays as arguments and checks whether the two arrays are of the same type. If the arrays are of different types, a new <xref:System.ArrayTypeMismatchException> is thrown and then caught in the calling method.  \\n  \\n [!code-cpp[ArrayTypeMisMatch_Constructor1#1](~/samples/snippets/cpp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor1/CPP/arraytypemismatch_constructor1.cpp#1)]\\n [!code-csharp[ArrayTypeMisMatch_Constructor1#1](~/samples/snippets/csharp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor1/CS/arraytypemismatch_constructor1.cs#1)]\\n [!code-vb[ArrayTypeMisMatch_Constructor1#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor1/VB/arraytypemismatch_constructor1.vb#1)]\"\n  syntax:\n    content: public ArrayTypeMismatchException ();\n    parameters: []\n  overload: System.ArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArrayTypeMismatchException.#ctor(System.String)\n  commentId: M:System.ArrayTypeMismatchException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.ArrayTypeMismatchException\n  langs:\n  - csharp\n  name: ArrayTypeMismatchException(String)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(String)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(String)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message.\n  remarks: \"The content of the `message` parameter is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|A null reference (`Nothing` in Visual Basic).|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  example:\n  - \"The following example demonstrates the ArrayTypeMismatchException(String) constructor of the <xref:System.ArrayTypeMismatchException> class. It contains a function which takes two arrays as arguments and checks whether the two arrays are of the same type. If the arrays are of different types, a new <xref:System.ArrayTypeMismatchException> is thrown and then caught in the calling method.  \\n  \\n [!code-cpp[ArrayTypeMisMatch_Constructor2#1](~/samples/snippets/cpp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor2/CPP/arraytypemismatch_constructor2.cpp#1)]\\n [!code-csharp[ArrayTypeMisMatch_Constructor2#1](~/samples/snippets/csharp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor2/CS/arraytypemismatch_constructor2.cs#1)]\\n [!code-vb[ArrayTypeMisMatch_Constructor2#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor2/VB/arraytypemismatch_constructor2.vb#1)]\"\n  syntax:\n    content: public ArrayTypeMismatchException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: A <xref href=\"System.String\"></xref> that describes the error.\n  overload: System.ArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  commentId: M:System.ArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.ArrayTypeMismatchException\n  langs:\n  - csharp\n  name: ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  type: Constructor\n  assemblies:\n  - mscorlib\n  - netstandard\n  - System.Runtime\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream. For more information, see [XML and SOAP Serialization](~/docs/framework/serialization/xml-and-soap-serialization.md).\n  syntax:\n    content: protected ArrayTypeMismatchException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The contextual information about the source or destination.\n  overload: System.ArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\n- uid: System.ArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  commentId: M:System.ArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.ArrayTypeMismatchException\n  langs:\n  - csharp\n  name: ArrayTypeMismatchException(String, Exception)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(String, Exception)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(String, Exception)\n  type: Constructor\n  assemblies:\n  - System.Runtime\n  - mscorlib\n  - netstandard\n  namespace: System\n  summary: Initializes a new instance of the <xref href=\"System.ArrayTypeMismatchException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor, or a null reference (`Nothing` in Visual Basic) if the <xref:System.Exception.InnerException%2A> property does not supply the inner exception value to the constructor.  \\n  \\n The following table shows the initial property values for an instance of <xref:System.ArrayTypeMismatchException>.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  example:\n  - \"The following code example demonstrates the <xref:System.ArrayTypeMismatchException.%23ctor%2A> constructor of the <xref:System.ArrayTypeMismatchException> class. It contains a function that takes two arrays as arguments and checks whether the two arrays are of the same type. If the arrays are of different types, a new <xref:System.ArrayTypeMismatchException> is thrown and then caught in the calling method.  \\n  \\n [!code-cpp[ArrayTypeMisMatch_Constructor3#1](~/samples/snippets/cpp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor3/CPP/arraytypemismatch_constructor3.cpp#1)]\\n [!code-csharp[ArrayTypeMisMatch_Constructor3#1](~/samples/snippets/csharp/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor3/CS/arraytypemismatch_constructor3.cs#1)]\\n [!code-vb[ArrayTypeMisMatch_Constructor3#1](~/samples/snippets/visualbasic/VS_Snippets_CLR/ArrayTypeMisMatch_Constructor3/VB/arraytypemismatch_constructor3.vb#1)]\"\n  syntax:\n    content: public ArrayTypeMismatchException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: innerException\n      type: System.Exception\n      description: The exception that is the cause of the current exception. If the <code>innerException</code> parameter is not a null reference, the current exception is raised in a `catch` block that handles the inner exception.\n  overload: System.ArrayTypeMismatchException.#ctor*\n  exceptions: []\n  version:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n  ms.technology:\n  - dotnet-standard\n  author: rpetrusha\n  ms.author: ronpet\n  manager: wpickett\nreferences:\n- uid: System.Exception\n  parent: System\n  isExternal: false\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.ArrayTypeMismatchException.#ctor\n  parent: System.ArrayTypeMismatchException\n  isExternal: false\n  name: ArrayTypeMismatchException()\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException()\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException()\n- uid: System.ArrayTypeMismatchException.#ctor(System.String)\n  parent: System.ArrayTypeMismatchException\n  isExternal: false\n  name: ArrayTypeMismatchException(String)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(String)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(String)\n- uid: System.String\n  parent: System\n  isExternal: false\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.ArrayTypeMismatchException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.ArrayTypeMismatchException\n  isExternal: false\n  name: ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(SerializationInfo, StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.ArrayTypeMismatchException.#ctor(System.String,System.Exception)\n  parent: System.ArrayTypeMismatchException\n  isExternal: false\n  name: ArrayTypeMismatchException(String, Exception)\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException(String, Exception)\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException(String, Exception)\n- uid: System.ArrayTypeMismatchException.#ctor*\n  parent: System.ArrayTypeMismatchException\n  isExternal: false\n  name: ArrayTypeMismatchException\n  nameWithType: ArrayTypeMismatchException.ArrayTypeMismatchException\n  fullName: ArrayTypeMismatchException.ArrayTypeMismatchException\n  monikers:\n  - netcore-1.0\n  - netcore-1.1\n  - netcore-2.0\n  - netframework-4.5.1\n  - netframework-4.5.2\n  - netframework-4.5\n  - netframework-4.6.1\n  - netframework-4.6.2\n  - netframework-4.6\n  - netframework-4.7\n  - netstandard-1.0\n  - netstandard-1.1\n  - netstandard-1.2\n  - netstandard-1.3\n  - netstandard-1.4\n  - netstandard-1.5\n  - netstandard-1.6\n  - netstandard-2.0\n  - xamarinandroid-7.1\n  - xamarinios-10.8\n  - xamarinmac-3.0\n  content_git_url: https://github.com/dotnet/docs/blob/master/xml/System/ArrayTypeMismatchException.xml\n- uid: System.Object.Equals(System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object)\n  nameWithType: Object.Equals(Object)\n  fullName: Object.Equals(Object)\n- uid: System.Object.Equals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: Equals(Object, Object)\n  nameWithType: Object.Equals(Object, Object)\n  fullName: Object.Equals(Object, Object)\n- uid: System.Object.GetHashCode\n  parent: System.Object\n  isExternal: false\n  name: GetHashCode()\n  nameWithType: Object.GetHashCode()\n  fullName: Object.GetHashCode()\n- uid: System.Exception.GetType\n  parent: System.Exception\n  isExternal: false\n  name: GetType()\n  nameWithType: Exception.GetType()\n  fullName: Exception.GetType()\n- uid: System.Object.MemberwiseClone\n  parent: System.Object\n  isExternal: false\n  name: MemberwiseClone()\n  nameWithType: Object.MemberwiseClone()\n  fullName: Object.MemberwiseClone()\n- uid: System.Object.ReferenceEquals(System.Object,System.Object)\n  parent: System.Object\n  isExternal: false\n  name: ReferenceEquals(Object, Object)\n  nameWithType: Object.ReferenceEquals(Object, Object)\n  fullName: Object.ReferenceEquals(Object, Object)\n- uid: System.Exception.ToString\n  parent: System.Exception\n  isExternal: false\n  name: ToString()\n  nameWithType: Exception.ToString()\n  fullName: Exception.ToString()\n- uid: System.Exception.Data\n  parent: System.Exception\n  isExternal: false\n  name: Data\n  nameWithType: Exception.Data\n  fullName: Exception.Data\n- uid: System.Exception.GetBaseException\n  parent: System.Exception\n  isExternal: false\n  name: GetBaseException()\n  nameWithType: Exception.GetBaseException()\n  fullName: Exception.GetBaseException()\n- uid: System.Exception.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Exception\n  isExternal: false\n  name: GetObjectData(SerializationInfo, StreamingContext)\n  nameWithType: Exception.GetObjectData(SerializationInfo, StreamingContext)\n  fullName: Exception.GetObjectData(SerializationInfo, StreamingContext)\n- uid: System.Exception.HelpLink\n  parent: System.Exception\n  isExternal: false\n  name: HelpLink\n  nameWithType: Exception.HelpLink\n  fullName: Exception.HelpLink\n- uid: System.Exception.HResult\n  parent: System.Exception\n  isExternal: false\n  name: HResult\n  nameWithType: Exception.HResult\n  fullName: Exception.HResult\n- uid: System.Exception.InnerException\n  parent: System.Exception\n  isExternal: false\n  name: InnerException\n  nameWithType: Exception.InnerException\n  fullName: Exception.InnerException\n- uid: System.Exception.Message\n  parent: System.Exception\n  isExternal: false\n  name: Message\n  nameWithType: Exception.Message\n  fullName: Exception.Message\n- uid: System.Exception.SerializeObjectState\n  parent: System.Exception\n  isExternal: false\n  name: SerializeObjectState\n  nameWithType: Exception.SerializeObjectState\n  fullName: Exception.SerializeObjectState\n- uid: System.Exception.Source\n  parent: System.Exception\n  isExternal: false\n  name: Source\n  nameWithType: Exception.Source\n  fullName: Exception.Source\n- uid: System.Exception.StackTrace\n  parent: System.Exception\n  isExternal: false\n  name: StackTrace\n  nameWithType: Exception.StackTrace\n  fullName: Exception.StackTrace\n- uid: System.Exception.TargetSite\n  parent: System.Exception\n  isExternal: false\n  name: TargetSite\n  nameWithType: Exception.TargetSite\n  fullName: Exception.TargetSite\n"}